window.LEADS = [
  {
    "company": "WITRON Logistik + Informatik GmbH",
    "website": "https://witron.de/",
    "region": "Deutschland",
    "location": "Parkstein, Deutschland",
    "industry": "Intralogistik / Fördertechnik",
    "description": "7.500 Beschäftigte weltweit, davon 2.500 in Parkstein (2026)",
    "need": "2025: Rekordauftragseingang über 2 Mrd. EUR; neue automatisierte Lebensmittel-Logistikprojekte und mechanische Komponentenentwicklung.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "98/100",
    "priority": "A",
    "next": "Beschaffung zu Kapazitätsspitzen und Make-or-buy für mechanische Module qualifizieren.",
    "sources": "https://witron.de/en/news/record-order-intake-in-the-companys-history | https://witron.de/en/ | Altbestand: https://www.witron.com/ ; https://careers.witron.com/",
    "date": "2026-08-12"
  },
  {
    "company": "STADLER Anlagenbau GmbH",
    "website": "https://w-stadler.de/",
    "region": "Deutschland",
    "location": "Altshausen, Deutschland",
    "industry": "Anlagenbau / Sortier- und Fördertechnik",
    "description": "knapp 650 Beschäftigte",
    "need": "2026: neuer Air Drum Sifter und neue hochautomatisierte Sortieranlagen; über 600 realisierte Anlagen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Bedarf für Antriebs- und Positionierkomponenten in neuen Sortiermodulen prüfen.",
    "sources": "https://w-stadler.de/en/ | https://w-stadler.de/en/company",
    "date": "2026-08-12"
  },
  {
    "company": "Dürr Group / Dürr Systems AG",
    "website": "https://www.durr-group.com/",
    "region": "Deutschland",
    "location": "Bietigheim-Bissingen, Deutschland",
    "industry": "Maschinen- und Anlagenbau / Automation",
    "description": "17.881 Beschäftigte (31.12.2025)",
    "need": "2025/26: Sustainable.Automation als Kernstrategie; Q4-Auftragseingang +19,9 % und Effizienzprogramm bei BBS Automation.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Materialgruppen für mechanische Sonderteile und Automationsbaugruppen der deutschen Standorte identifizieren.",
    "sources": "https://www.durr-group.com/en/company/overview | https://www.durr-group.com/en/media/news/news-detail/view/duerr-group-significantly-improves-profitability-114080",
    "date": "2026-08-12"
  },
  {
    "company": "Mikron Group",
    "website": "https://www.mikron.com/",
    "region": "Schweiz",
    "location": "Boudry, Schweiz",
    "industry": "Automation / Präzisionsmaschinenbau",
    "description": "1.570 Beschäftigte (Ende 2025)",
    "need": "2025: Automation-Umsatz auf CHF 250,1 Mio. gestiegen; solider Auftragsbestand und starke Nachfrage aus Pharma/Diagnostik in Europa.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "95/100",
    "priority": "A",
    "next": "Schweizer Automation-Standorte zu Präzisionsteilen und vormontierten mechanischen Einheiten qualifizieren.",
    "sources": "https://2025.report.mikron.com/wp-content/uploads/2026/02/Mikron_Annual_Report_2025.pdf | https://2025.report.mikron.com/key-figures/spreadsheet/",
    "date": "2026-08-12"
  },
  {
    "company": "teamtechnik Industrieausrüstung GmbH",
    "website": "https://teamtechnik.de/",
    "region": "Deutschland",
    "location": "Freiberg am Neckar, Deutschland",
    "industry": "Montage- und Prüftechnik / Automation",
    "description": "Gruppenbeleg: über 300 Beschäftigte allein bei der polnischen Automationseinheit",
    "need": "2025: organisatorische Bündelung und Fortführung kundenspezifischer automatisierter Montage- und Prüflinien; Komponentenfertigung an mehreren Standorten.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Aktuelle Beschaffungsorganisation und Fremdvergabe für Montage-/Prüfanlagen verifizieren.",
    "sources": "https://teamtechnik.de/ueber-uns/ | https://teamtechnik.pl/en/about-us/ | https://teamtechnik.pl/en/next-starts-now-2/",
    "date": "2026-08-12"
  },
  {
    "company": "KNOLL Maschinenbau GmbH",
    "website": "https://www.knoll-mb.de/",
    "region": "Deutschland",
    "location": "Bad Saulgau, Deutschland",
    "industry": "Fördertechnik / Maschinenbau / Automation",
    "description": "rund 1.200 Beschäftigte weltweit (2025)",
    "need": "2025/26: neue automatisierte Späneentsorgung, Click.it-Automation, Ausbau der US-Montage und Übernahme von Mercatus.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Bad Saulgau zu Sonderteilen, Antriebskomponenten und Kapazitätsspitzen qualifizieren.",
    "sources": "https://www.knoll-mb.de/en/ | https://www.knoll-mb.de/en/news/company/55-years-knoll | https://www.knoll-mb.de/en/news/press-release/stronger-presence-in-the-usa",
    "date": "2026-08-12"
  },
  {
    "company": "Bystronic AG",
    "website": "https://www.bystronic.com/",
    "region": "Schweiz",
    "location": "Niederönz, Schweiz",
    "industry": "Maschinenbau / Blechbearbeitung / Automation",
    "description": "über 2.900 Beschäftigte weltweit (2025)",
    "need": "2025: Smart-Factory-Konzept sowie neue Biege- und Laserautomation; Konsolidierung der Automationsproduktion.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Niederönz-Einkauf zu mechanischen Sonderteilen und modularen Automationsbaugruppen prüfen.",
    "sources": "https://report.bystronic.com/2025/bystronic | https://report.bystronic.com/2025/app/uploads/Annual-Report-2025.pdf",
    "date": "2026-08-12"
  },
  {
    "company": "Komax Group",
    "website": "https://www.komaxgroup.com/",
    "region": "Schweiz",
    "location": "Dierikon, Schweiz",
    "industry": "Automatisierter Maschinenbau / Kabelverarbeitung",
    "description": "3.167 Beschäftigte (31.12.2025)",
    "need": "2025: CHF 70,9 Mio. F&E, mehrere neue Maschinen und Inline-Prüfsysteme; 633 Mitarbeitende in F&E/Engineering.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Schweizer Beschaffung für kundenspezifische Anwendungen, Präzisionsteile und Baugruppen qualifizieren.",
    "sources": "https://www.komaxgroup.com/en/annualreport2025 | https://www.komaxgroup.com/en/annualreport2025/innovation",
    "date": "2026-08-12"
  },
  {
    "company": "Bühler Group",
    "website": "https://www.buhlergroup.com/",
    "region": "Schweiz",
    "location": "Uzwil, Schweiz",
    "industry": "Lebensmittelmaschinen / Anlagenbau / Automation",
    "description": "12.090 Beschäftigte (2025)",
    "need": "2026: neue Finer S und ELK S Edition 26 mit geänderten Maschinenrahmen, IE5-Antrieben und neuer Automation.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "95/100",
    "priority": "A",
    "next": "Chocolate-&-Coffee-Beschaffung in Uzwil mit Bezug auf neue Edition-26-Module qualifizieren.",
    "sources": "https://annualreport.buhlergroup.com/reports/en_25/home.html | https://www.buhlergroup.com/global/en/media/media-releases/finer-s-ed-26-and-elk-s-ed-26.html",
    "date": "2026-08-12"
  },
  {
    "company": "psb intralogistics GmbH",
    "website": "https://www.psb-gmbh.de/",
    "region": "Deutschland",
    "location": "Pirmasens, Deutschland",
    "industry": "Intralogistik / Förder- und Lagertechnik",
    "description": "mehr als 520 Beschäftigte",
    "need": "2025/26: erfolgreicher Marktstart des autopick, neues Materialwirtschaftszentrum und neue automatische Lagerprojekte.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Materialwirtschaft zu Antriebselementen, Riemenscheiben und Zeichnungsteilen für Shuttle-/Sortiersysteme ansprechen.",
    "sources": "https://www.psb-gmbh.de/psb/ | https://www.psb-gmbh.de/news/ | https://www.psb-gmbh.de/news/sew-eurodrive-bruchsaal-psb-microstore/",
    "date": "2026-08-12"
  },
  {
    "company": "F.EE GmbH / F.EE-Unternehmensgruppe",
    "website": "https://www.fee.de/",
    "region": "Deutschland",
    "location": "Neunburg vorm Wald; weitere Niederlassungen u. a. Frankfurt und Leipzig",
    "industry": "Automatisierungstechnik, Maschinenbau, Robotik",
    "description": "ca. 1.050 Mitarbeitende laut Ausbildungsoffensive Bayern; offizielle F.EE-Seite nennt weltweite Mitarbeitendenzahl ebenfalls in dieser Größenordnung.",
    "need": "Mittleres bis starkes technisches Signal: F.EE bietet Universal-Verfahrachsen/Linearachsen für Roboter, Fördertechnik, Drehtische/Antriebe sowie Sondermaschinenbau und eigene Einzel-/Serienfertigung an. Das spricht für Bedarf an mechanischen Antriebselementen, Sonderteilen und Baugruppen, ohne aktuelle Beschaffungsabsicht zu belegen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung: passenden Einstieg über technischen Einkauf oder Leitung Maschinenbau/Robotik recherchieren; mit konkretem Bezug auf Linearachsen/Fördertechnik und Sonderteile ansprechen.",
    "sources": "https://www.fee.de/ ; https://www.fee.de/unternehmen/zahlen-fakten ; https://www.ausbildungsoffensive-bayern.de/mitgliedsunternehmen/profile/fee-industrieautomation-gmbh-u-co-kg-92431-neunburg-vorm-wald/",
    "date": "2026-07-31"
  },
  {
    "company": "ASS Maschinenbau GmbH",
    "website": "https://www.ass-automation.com/",
    "region": "Deutschland",
    "location": "Overath",
    "industry": "Robotik, Greifertechnik, Automatisierung, Maschinenbau",
    "description": "rund 120 Mitarbeitende laut offizieller Unternehmensseite",
    "need": "Mittleres technisches Signal: umfangreicher mechatronischer Komponentenbau, kundenspezifische Greiflösungen und Turn-Key-Automationsanlagen deuten auf Bedarf an Sonderteilen, mechanischen Baugruppen und Antriebskomponenten hin; keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "78/100",
    "priority": "B",
    "next": "Vor Ansprache technische Produkt-/Katalogtiefe prüfen; Einstieg über Sonderteile/Baugruppen für Greifer- und Automationsanlagen wählen.",
    "sources": "https://www.ass-automation.com/de/unternehmen/ass-maschinenbau-gmbh.html",
    "date": "2026-07-31"
  },
  {
    "company": "A+F Automation + Fördertechnik GmbH / EOL Group",
    "website": "https://eol.group/de/unternehmen/af-automationfoerdertechnik",
    "region": "Deutschland",
    "location": "Kirchlengern",
    "industry": "Verpackungsmaschinen, Fördertechnik, End-of-Line-Automation",
    "description": "A+F: 51-200 Beschäftigte laut LinkedIn; EOL Group: 330 Mitarbeitende laut CGS-Portfolio. Größenangabe ergänzend, nicht direkt aus A+F-Unternehmensseite.",
    "need": "Mittleres technisches Signal: individuelle Endverpackungs- und Palettieranlagen mit Pick-and-place, Robotik und Transportsystemen legen Bedarf an Antriebselementen, Förder-/Positionierkomponenten und Sonderbaugruppen nahe; aktuelle Beschaffungsabsicht nicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "82/100",
    "priority": "A",
    "next": "Vertriebsprüfung mit Fokus auf Ersatz-/Sonderteile, Fördertechnik-Komponenten und Baugruppen für End-of-Line-Anlagen; Lieferanten-/Einkaufsstruktur der EOL Group klären.",
    "sources": "https://eol.group/de/unternehmen/af-automationfoerdertechnik ; https://www.wlw.de/de/firma/af-automation-foerdertechnik-gmbh-344825 ; https://www.cgs-management.com/en/portfolio/eol-packaging-experts",
    "date": "2026-07-31"
  },
  {
    "company": "DFT - Dürkopp Fördertechnik GmbH",
    "website": "https://www.duerkopp.com/de/",
    "region": "Deutschland",
    "location": "Bielefeld",
    "industry": "Intralogistik, Fördertechnik, Anlagenbau, Automatisierungsanlagen",
    "description": "ca. 550+ Mitarbeitende laut OWL Maschinenbau; LinkedIn nennt 501-1.000 Beschäftigte.",
    "need": "Starkes technisches Signal: offizielle DFT-/OWL-Quellen belegen automatisierte Sortier- und Fördertechnik, Hängefördertechnik und Anlagenbau für Intralogistik. Laufende Jobs/Projektplanung deuten auf Angebotslayouts und Materiallisten für Projekte hin. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung mit Fokus auf mechanische Antriebselemente und Sonder-/Baugruppen für Sortier- und Hängefördermodule; Einkaufsweg über DFT vs. KNAPP klären.",
    "sources": "https://www.duerkopp.com/de/ ; https://www.owl-maschinenbau.de/unternehmen/dft-duerkopp-foerdertechnik-gmbh/ ; https://de.linkedin.com/company/dft-duerkopp ; https://haystackapp.io/jobs/5675456f-bde8-4928-b053-120eff8aaa65",
    "date": "2026-07-31"
  },
  {
    "company": "MINDA Industrieanlagen GmbH",
    "website": "https://www.minda.com/de/",
    "region": "Deutschland",
    "location": "Minden",
    "industry": "Anlagenbau, Intralogistik, Fördertechnik",
    "description": "ca. 230 Mitarbeitende laut Stadt Minden.",
    "need": "Starkes technisches Signal: offizielle Quellen belegen kundenspezifische Fördertechnik und Intralogistiksysteme; Stadt Minden bestätigt Entwicklung und Produktion am Standort. Forbo-Fallbeispiel nennt Spezialanlagenbau und interne Materialflusslösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Ansprache auf Sonderteile/Baugruppen und Antriebskomponenten für kundenspezifische Förder-/Transportanlagen vorbereiten; Einkaufs-/Konstruktionsrollen recherchieren.",
    "sources": "https://www.minda.com/de/ ; https://www.minda.com/en/ ; https://www.owl-maschinenbau.de/unternehmen/minda-industrieanlagen-gmbh/ ; https://www.minden.de/wirtschaft-mobilitaet-wohnen/standort-minden/arbeiten-in-minden/minda/ ; https://www.forbo.com/movement/en-gl/about-us/winning-solutions/minda-industrieanlagen-gmbh/p4qqvm",
    "date": "2026-07-31"
  },
  {
    "company": "GHD Georg Hartmann Maschinenbau GmbH",
    "website": "https://www.ghd.net/de/startseite",
    "region": "Deutschland",
    "location": "Delbrück",
    "industry": "Maschinenbau, Lebensmittel- und Verpackungsmaschinen",
    "description": "201-500 Beschäftigte laut LinkedIn; Größe ergänzend über Messeprofile plausibilisiert.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Produktseite nennt komplette Maschinen/Anlagen zum Schneiden und Verpacken; Messeprofile bestätigen führende Rolle in Schneide-/Verpackungsmaschinen. Das legt Bedarf an Sonderteilen, Baugruppen und Antriebselementen nahe. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "80/100",
    "priority": "A",
    "next": "Vor Ansprache technische Produkt-/Ersatzteilinformationen prüfen; Einstieg über Sonderteile/Baugruppen für Schneide- und Verpackungsanlagen.",
    "sources": "https://www.ghd.net/de/startseite ; https://de.linkedin.com/company/ghd-georg-hartmann-maschinenbau-gmbh ; https://www.iba-tradefair.com/en/discover/all-exhibitors-and-suppliers/ghd-georg-hartmann-maschinenbau-gmbh ; https://www.interpack.com/vis/v1/en/exhprofiles/BSN93PqHQUyR4I82jEZNjQ",
    "date": "2026-07-31"
  },
  {
    "company": "HAVER & BOECKER OHG / Machinery Division",
    "website": "https://www.haverboecker.com/de/",
    "region": "Deutschland",
    "location": "Oelde",
    "industry": "Verpackungstechnologie, Maschinenbau, Anlagenbau",
    "description": "ca. 3.000 Mitarbeitende laut öffentlich zugänglicher Unternehmens-/Profilangaben; weltweit mit zahlreichen Tochtergesellschaften/Vertretungen.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Seite belegt individuelle Maschinenlösungen und Verpackungstechnologie; Machinery-Division-Profile belegen Entwicklung und Produktion von Systemen/Anlagen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "79/100",
    "priority": "B",
    "next": "Als strategischen Prüflead aufnehmen; spezifische Einkaufs-/Konstruktionskontakte der Machinery Division und Lieferantenanforderungen recherchieren.",
    "sources": "https://www.haverboecker.com/de/ ; https://be.linkedin.com/company/haver-boecker-machinery-division ; https://www.at-minerals.com/en/artikel/at_HAVER_BOECKER_Machinery_Division-3323544.html",
    "date": "2026-07-31"
  },
  {
    "company": "Lödige Industries GmbH",
    "website": "https://www.lodige.com/de-de/",
    "region": "Deutschland",
    "location": "Warburg/Scherfede; Paderborn",
    "industry": "Fördertechnik, Intralogistik, Logistiksysteme, Materialflusslösungen",
    "description": "mehr als 1.500 Mitarbeitende laut LinkedIn; weitere öffentliche Profile nennen über 1.300 weltweit.",
    "need": "Starkes technisches Signal: offizielle Seite belegt kundenspezifische Materialflusslösungen und Heavy-Goods-Movement; deutsche Standortseite nennt Fördertechnik und Produktionslogistik. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "82/100",
    "priority": "A",
    "next": "Vertriebsprüfung auf Produktionslogistik-/Fördertechnikkomponenten; passende Rollen am Standort Paderborn/Warburg und zentrale Einkaufsstruktur identifizieren.",
    "sources": "https://www.lodige.com/en-global/ ; https://www.lodige.com/de-de/unternehmen/wo-sie-uns-finden/deutschland/ ; https://de.linkedin.com/company/lodige-industries",
    "date": "2026-07-31"
  },
  {
    "company": "Vanderlande Industries B.V.",
    "website": "https://www.vanderlande.com/",
    "region": "Niederlande",
    "location": "Veghel",
    "industry": "Intralogistik, Fördertechnik, Logistikprozess-Automation, Anlagenbau",
    "description": "3.491 FTE bei Vanderlande Industries B.V. per 31.03.2025; davon 828 außerhalb der Niederlande laut Annual Report FY2025. Weitere Konzernquellen nennen >10.000 weltweit.",
    "need": "Starkes technisches Signal: offizielle Website nennt integrierte Logistikautomationssysteme; Karrierequelle nennt 3D-Conveyor-Modelle, mechanische Layouts, Schnittstellen zu Equipment und Procurement; FY2025-Bericht belegt Design/Implementation von logistischen Automationslösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung mit Fokus auf mechanische Antriebselemente, Sonderteile und Baugruppen für Förder-/Sortier-/BHS-Module; Einstieg über Procurement Cost Engineering oder Mechanical Engineering am Standort Veghel prüfen.",
    "sources": "https://www.vanderlande.com/ ; https://careers.vanderlande.com/all-jobs/mechanical-project-engineer-i-jr36845/ ; https://careers.vanderlande.com/job-areas/engineering/ ; https://www.vanderlande.com/wp-content/uploads/2025/11/Vanderlande-Industries-B.V.-annual-report-FY25-incl.-auditors-report.pdf",
    "date": "2026-07-31"
  },
  {
    "company": "AWL-Techniek B.V. / AWL Automation",
    "website": "https://awlautomation.com/",
    "region": "Niederlande",
    "location": "Harderwijk, Gelderland",
    "industry": "Robotik, industrielle Automation, Sondermaschinenbau, Intralogistik",
    "description": "Über 700 Mitarbeitende weltweit laut A3-Profil; LinkedIn-Snippets nennen ca. 750+.",
    "need": "Starkes technisches Signal: offizielle Website belegt robotic automation für Produktions- und Intralogistikprozesse, Pick & Place, Parcel Induction, Tote Handling und End-of-arm tooling; A3-Profil belegt Design und Bau smarter modularer Maschinen. Aktuelle Karrierequelle nennt Mechanical Engineer in Harderwijk. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Vor Ansprache Einkaufs-/Engineering-Leitung öffentlich nachrecherchieren; Erstansatz über Sonderteile/Baugruppen für Robotikzellen, End-of-arm tooling und Material-Handling-Module.",
    "sources": "https://awlautomation.com/ ; https://www.automate.org/companies/awl-techniek-b-v ; https://careers.awl.nl/professional/",
    "date": "2026-07-31"
  },
  {
    "company": "BluePrint Automation B.V.",
    "website": "https://www.blueprintautomation.com/",
    "region": "Niederlande",
    "location": "Woerden, Utrecht",
    "industry": "Verpackungstechnik, Verpackungsautomation, Robotik, Maschinenbau",
    "description": "Über 500 Mitarbeitende weltweit laut offizieller Teamseite; LinkedIn/weitere Profile ergänzend 201-500 bzw. >550.",
    "need": "Starkes technisches Signal: offizielle Website belegt Entwicklung und Fertigung automatisierter Verpackungsmaschinen mit Pick-and-place und vision-guided robotics; Karriereportal 2026 nennt Stellen in Woerden für Industrial Automation, Electrical Design, Mechatronik, Machinebankwerker/Fabricage und Werkvoorbereiding Service; Stellenbeschreibung nennt Upgrades/Modifikationen bestehender Maschinen und Zusammenarbeit mit Mechanical-/Software-/Service-Engineering. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Vertriebsprüfung mit konkretem Bezug auf Sonderteile/Baugruppen und Antriebskomponenten für Verpackungs-, Pick-and-place- und Service-/Retrofit-Anwendungen; Einstieg über Engineering/Operations oder Material Planning prüfen.",
    "sources": "https://www.blueprintautomation.com/ ; https://www.blueprintautomation.com/bpa-global/team ; https://jobs.blueprintautomation.com/ ; https://jobs.blueprintautomation.com/vacatures/electrical-engineer.html",
    "date": "2026-07-31"
  },
  {
    "company": "Krones AG",
    "website": "https://www.krones.com/",
    "region": "Deutschland",
    "location": "Neutraubling",
    "industry": "Verpackungs- und Abfülltechnik, Anlagenbau",
    "description": "20.379 Mitarbeitende 2024 laut Krones-IR-Präsentation; Größe belastbar.",
    "need": "Mittleres bis starkes Signal: offizielle Website belegt Prozess-, Füll- und Verpackungsmaschinen; Engineering-/Karrierequellen zeigen Mechanikbezug. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "84/100",
    "priority": "A",
    "next": "Lieferanten-/Einkaufszugang prüfen; Einstieg über Spezialteile, Ersatz-/Servicebedarf oder Kleinserien für Packaging/Materialfluss.",
    "sources": "https://www.krones.com/en/index.php ; https://www.krones.com/en/company/investor-relations/krones-group-annual-report-2025.php ; https://www.krones.com/en/career/engineering.php",
    "date": "2026-08-03"
  },
  {
    "company": "Gerhard Schubert GmbH Verpackungsmaschinen",
    "website": "https://www.schubert.group/",
    "region": "Deutschland",
    "location": "Crailsheim",
    "industry": "Verpackungsmaschinen, Robotik, Automatisierung",
    "description": "1.900 Mitarbeitende weltweit laut offizieller Arbeitgeberseite.",
    "need": "Starkes Signal: offizielle Arbeitgeberseite belegt Größe und Robotik-/Verpackungsfokus; RoboJob-Fallstudie belegt eigene Komponentenfertigung und regionales Lieferantennetzwerk. Keine aktuelle Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Einstieg über Komponentenfertigung/Sonderteile und Lieferantenfähigkeit für mechanische Baugruppen prüfen.",
    "sources": "https://www.schubert.group/en/careers/schubert-as-an-employer/ ; https://robojob.eu/en/2000-installations/customer-testimonials/gerhard-schubert-gmbh/",
    "date": "2026-08-03"
  },
  {
    "company": "MULTIVAC Group",
    "website": "https://multivac.com/",
    "region": "Deutschland",
    "location": "Wolfertschwenden",
    "industry": "Verpackungsmaschinen, Lebensmitteltechnik, Linienbau",
    "description": "Mehrere Tausend Mitarbeitende laut offizieller Seite; ergänzende Profile nennen rund 7.800 weltweit.",
    "need": "Mittleres Signal: offizielle Seite belegt Maschinen und Linien; Stellenquelle für Mechanical Product Design im Tray-/Pouch-Packaging zeigt laufenden mechanischen Entwicklungsbedarf. Keine Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "82/100",
    "priority": "A",
    "next": "DACH-Einkaufs-/Engineering-Rolle ermitteln und mit mechanischen Sonder-/Verschleißteilen sowie Baugruppen ansetzen.",
    "sources": "https://multivac.com/int/en/company/multivac-group ; https://multivac.com/bg/en/career/job-vacancies/vacancies.mechanical-product-designer-tray-pouch-packaging-mubg",
    "date": "2026-08-03"
  },
  {
    "company": "Grenzebach Group",
    "website": "https://www.grenzebach.com/",
    "region": "Deutschland",
    "location": "Asbach-Bäumenheim / Hamlar",
    "industry": "Industrieautomation, Anlagenbau, Intralogistik",
    "description": "1.600 Mitarbeitende und 9 Produktions-/Entwicklungsstandorte laut offizieller Website.",
    "need": "Mittleres Signal: offizielle Website belegt industrielle Automation und Intralogistik; Engineering-Seite beschreibt Produktdesign, Konstruktion und Entwicklung über mehrere Business Units. Keine Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "83/100",
    "priority": "A",
    "next": "Business Unit Intralogistics oder Special Technologies zuerst qualifizieren und Projekt-/Einkaufsrollen identifizieren.",
    "sources": "https://www.grenzebach.com/en/ ; https://www.grenzebach.com/en/career/career-level-experienced-professionals/direct-entry/functional-area-of-product-design-/-engineering/",
    "date": "2026-08-03"
  },
  {
    "company": "Kardex Mlog / Kardex",
    "website": "https://www.kardex.com/",
    "region": "Deutschland",
    "location": "Neuenstadt am Kocher",
    "industry": "Intralogistik, automatische Lager- und Materialflusssysteme",
    "description": "Rund 2.900 Mitarbeitende weltweit laut offizieller Karriereseite; drei Produktionsstandorte in Deutschland.",
    "need": "Mittleres bis starkes Signal: offizielle Quellen nennen automatisierte Produkte, Material Handling und deutsche Produktion; Karriereseite beschreibt Stacker Cranes, Shuttle Vehicles und Conveyor Systems. Keine Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "83/100",
    "priority": "A",
    "next": "Supplier-Quality-/Einkaufsrolle in Neuenstadt bzw. Deutschland prüfen; Bedarf für mechanische Baugruppen und Ersatzteile sondieren.",
    "sources": "https://www.kardex.com/company_people/careers/careers-at-kardex ; https://www.kardex.com/en-us/industry-applications/warehouse/mechanical-engineering",
    "date": "2026-08-03"
  },
  {
    "company": "OPTIMA packaging group GmbH",
    "website": "https://www.optima-packaging.com/de",
    "region": "Deutschland",
    "location": "Schwäbisch Hall",
    "industry": "Verpackungs- und Abfüllanlagen",
    "description": "Rund 3.700 Mitarbeitende laut ergänzendem Arbeitgeberprofil; große internationale Organisation durch offizielles Karriereportal belegt.",
    "need": "Mittleres Signal: offizielles Karriereportal zeigt zahlreiche technische Rollen; Profile nennen Arbeitsvorbereitung, Entwicklung von Werkzeugsystemen, Steuerungstechnik und Automation. Keine Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "82/100",
    "priority": "A",
    "next": "Technische Einkaufs-/Arbeitsvorbereitungsrollen in Schwäbisch Hall prüfen; Lieferantennutzen für Sonderteile und Baugruppen konkretisieren.",
    "sources": "https://www.optima-packaging.com/de ; https://www.optima-packaging.com/de/karriere ; https://www.optima-packaging.com/de/karriere/aktuelle-stellenangebote",
    "date": "2026-08-03"
  },
  {
    "company": "SSI SCHÄFER Group",
    "website": "https://www.ssi-schaefer.com/",
    "region": "Deutschland",
    "location": "Neunkirchen/Siegerland; Graz u. a.",
    "industry": "Intralogistik, Material Handling, Lagerautomatisierung",
    "description": "5.001-10.000 Beschäftigte laut ergänzendem LinkedIn-Unternehmensprofil; globale Unternehmensgruppe.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Website belegt modulare Intralogistiksysteme; technisches Unternehmensprofil zu SSI Schäfer PEEM beschreibt Entwicklung und Fertigung dynamischer Förderanlagen für Behälter und Kartons. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "87/100",
    "priority": "A",
    "next": "DACH-Einkaufsorganisation für Fördertechnik/Mechanik segmentieren und Lieferantenportal bzw. Materialgruppen prüfen.",
    "sources": "https://www.ssi-schaefer.com/ ; https://www.warehouse-logistics.com/download/Flyer/GB_Flyer_Firma_Salomon_002.pdf ; https://www.linkedin.com/company/ssischaefer",
    "date": "2026-08-03"
  },
  {
    "company": "BEUMER Group GmbH & Co. KG",
    "website": "https://www.beumergroup.com/",
    "region": "Deutschland",
    "location": "Beckum",
    "industry": "Fördertechnik, Intralogistik, Verpackung, Sortation",
    "description": "Mehr als 6.000 Mitarbeitende in über 70 Ländern laut offizieller Website (Stand der Direktprüfung 30.07.2026).",
    "need": "Starkes technisches Signal: offizielle Website belegt Förder-, Palettier-, Verpackungs- und Sortierlösungen sowie Lifecycle-Service. Dies spricht für mechanische Komponenten- und Ersatzteilbedarfe, ohne konkrete Beschaffungsabsicht zu belegen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Beschaffungsweg und Materialgruppen für mechanische Antriebselemente prüfen; Einstieg über Service-/Ersatzteil- oder Projektgeschäft vorbereiten.",
    "sources": "https://www.beumergroup.com/ ; https://www.beumergroup.com/career/",
    "date": "2026-08-03"
  },
  {
    "company": "HAHN Automation Group",
    "website": "https://www.hahnautomation.group/",
    "region": "Deutschland",
    "location": "Rheinböllen",
    "industry": "Sondermaschinenbau, Factory Automation, Robotik",
    "description": "Größenklasse über 50 klar; konkrete aktuelle Mitarbeiterzahl auf offizieller Karriereseite nicht auslesbar. Ergänzende Profile nennen rund 900.",
    "need": "Mittleres technisches Signal: offizielle Website belegt kundenspezifische Konstruktion und Integration physischer Automations-/Robotiksysteme; Karriereportal zeigte aktive technische Rekrutierung. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "78/100",
    "priority": "B",
    "next": "Standorte Rheinböllen und Diepenau nach Konstruktion und technischem Einkauf segmentieren; Größenbeleg vor Erstansprache nachziehen.",
    "sources": "https://www.hahnautomation.group/ ; https://careers.hahnautomation.group/ ; https://careers.hahnautomation.group/jobboard/",
    "date": "2026-08-03"
  },
  {
    "company": "Swisslog AG",
    "website": "https://www.swisslog.com/",
    "region": "Schweiz",
    "location": "Buchs AG; Dortmund u. a.",
    "industry": "Intralogistik, Warehouse Automation",
    "description": "Größe über 50 sicher; exakte aktuelle Swisslog-Mitarbeiterzahl in den geprüften Quellen nicht gefunden.",
    "need": "Mittleres bis starkes technisches Signal: eine direkt geprüfte Mechanical-Engineer-Stelle verlangte CAD sowie mechanische Installation für Automated Material Handling; weitere Projektquelle nannte Förderer, Krane und Monorail. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "76/100",
    "priority": "B",
    "next": "DACH-Organisation und Einkaufszugang klären; mechanische Subsysteme für Conveyor-, Stacker-Crane- und Monorail-Anwendungen fokussieren.",
    "sources": "https://www.swisslog.com/ ; https://www.swisslog.com/en-us/careers/openings/mechanical-engineer-4142 ; https://jobs.smartrecruiters.com/SwisslogUKLtd/743999703113380-maintenance-manager-automated-warehouse",
    "date": "2026-08-03"
  },
  {
    "company": "Mosca GmbH",
    "website": "https://www.mosca.com/",
    "region": "Deutschland",
    "location": "Waldbrunn",
    "industry": "Verpackungstechnik, End-of-Line-Automation",
    "description": "Größe über 50 plausibel; exakte aktuelle Mitarbeiterzahl in den geprüften offiziellen Quellen nicht gefunden.",
    "need": "Mittleres technisches Signal: offizielle Website belegt Umreifungsmaschinen und komplexe Systeme; ergänzende Konzernquelle zeigte Electro-Mechanical- und Engineering-Rollen für End-of-Line-Lösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "73/100",
    "priority": "B",
    "next": "Deutschen Einkauf/Engineering-Zugang und Größenbeleg verifizieren; mit Sonderteilen oder Baugruppen für Umreifungs-/Fördermodule ansetzen.",
    "sources": "https://www.mosca.com/ ; https://www.mosca.com/en/career ; https://www.eammosca.com/ ; https://www.eammosca.com/career",
    "date": "2026-08-03"
  },
  {
    "company": "Cama Group",
    "website": "https://camagroup.com/",
    "region": "Italien",
    "location": "Molteno (Lecco)",
    "industry": "Verpackungsmaschinen, Robotik, End-of-Line-Automation",
    "description": "250+ aktive Gruppenmitarbeitende laut offizieller Website.",
    "need": "Starkes aktuelles technisches Signal: Interpack-2026-Portfolio mit drei real vorgeführten hochrobotisierten Maschinen, modularen Monobloc-Systemen, Servo- und eigener Robotiktechnologie.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Technischen Einkauf bzw. Mechanical Engineering identifizieren und mit Sonderteilen/Baugruppen für Servo-, Robotik- und Verpackungsmodule ansprechen.",
    "sources": "https://camagroup.com/ ; https://camagroup.com/cama-group-at-interpack-2026/ ; https://camagroup.com/packaging-lines/",
    "date": "2026-08-04"
  },
  {
    "company": "Marchesini Group S.p.A.",
    "website": "https://www.marchesini.com/",
    "region": "Italien",
    "location": "Pianoro / Bologna",
    "industry": "Pharma- und Kosmetik-Verpackungsmaschinen",
    "description": "2.874 Mitarbeitende zum 31.12.2024 laut Nachhaltigkeitsbericht 2024.",
    "need": "Starkes Signal: aktuelle Maschinen-/Linienangebote, eigene Produktion und Montage; offizielle Stellenbeschreibung 2026 nennt mechanische Montage, technische Zeichnungen sowie FAT/SAT automatischer Verpackungsmaschinen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Lieferanten- und Einkaufszugang in Pianoro prüfen; Einstieg über formatabhängige Sonderteile, Baugruppen und mechanische Ersatzteile vorbereiten.",
    "sources": "https://www.marchesini.com/en/corporate/the-group ; https://www.marchesini.com/en/corporate/work-with-us/mechanical-fitter ; https://www.marchesini.com/sites/default/files/2025-12/Sustainability%20Report%202024.pdf",
    "date": "2026-08-04"
  },
  {
    "company": "IMA Group",
    "website": "https://imagroup.com/",
    "region": "Italien",
    "location": "Ozzano dell'Emilia / Bologna",
    "industry": "Verpackungsmaschinen, Pharma-, Food- und Industrieautomation",
    "description": "Großgruppe mit 56 Produktionsstandorten und Aktivitäten in 80 Ländern; deutlich über 50 Beschäftigte, exakte 2025-Gesamtzahl im geprüften Webtext nicht ausgewiesen.",
    "need": "Starkes aktuelles Signal: offizieller Investorbereich 2026 bestätigt Entwicklung und Produktion automatischer Maschinen sowie 56 Manufacturing Sites; 2025-Nachhaltigkeitsbericht ist veröffentlicht.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "87/100",
    "priority": "A",
    "next": "Zunächst passende italienische Business Unit und Materialgruppe identifizieren; Spezial-/Formatteile oder Baugruppen statt generischer Konzernansprache fokussieren.",
    "sources": "https://imagroup.com/corporate/investors/ ; https://imagroup.com/",
    "date": "2026-08-04"
  },
  {
    "company": "Cimcorp Group",
    "website": "https://cimcorp.com/",
    "region": "Finnland",
    "location": "Ulvila",
    "industry": "Intralogistik, Robotik, Materialflussautomation",
    "description": "516 Gruppenmitarbeitende laut Nachhaltigkeitsbericht 2025.",
    "need": "Starkes Signal: Nachhaltigkeitsbericht 2025 belegt 516 Mitarbeitende sowie Design, Fertigung, Installation und Support von Automation einschließlich Upgrades und Ersatzteilen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Procurement oder Mechanical Engineering in Ulvila ansprechen; mechanische Baugruppen, Sonderteile und Lifecycle-Ersatzteile als Einstieg priorisieren.",
    "sources": "https://cimcorp.com/ ; https://cimcorp.com/app/uploads/2026/04/Cimcorp-Group-Sustainability-report.pdf ; https://cimcorp.com/career-opportunities/open-application/",
    "date": "2026-08-04"
  },
  {
    "company": "Coesia S.p.A.",
    "website": "https://www.coesia.com/",
    "region": "Italien",
    "location": "Bologna",
    "industry": "Verpackungsmaschinen, Industrieautomation, Intralogistik",
    "description": "8.000+ Mitarbeitende, 84 Produktionswerke und 127 operative Einheiten laut offizieller Gruppenseite.",
    "need": "Starkes Signal: offizielle 2025/2026-Seiten zeigen neue Verpackungsmaschinen, robotische Food-Handhabung, AI-Palettierung und ein breites Produktionsnetz.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "78/100",
    "priority": "B",
    "next": "Vor Ansprache eine konkrete Coesia-Marke ohne direkten Komponentenwettbewerb auswählen und deren lokalen Einkauf prüfen.",
    "sources": "https://www.coesia.com/en/group/coesia ; https://www.coesia.com/en/exhibitions/coesia-at-pack-expo-las-vegas-2025-dive-into-the-automation-evolution ; https://www.coesia.com/en",
    "date": "2026-08-04"
  },
  {
    "company": "Sidel",
    "website": "https://www.sidel.com/",
    "region": "Frankreich",
    "location": "Octeville-sur-Mer; Parma u. a.",
    "industry": "Abfüll- und Verpackungslinien, Robotik, End-of-Line",
    "description": "Große internationale Unternehmensgruppe und Teil von Tetra Laval; deutlich über 50 Beschäftigte, exakte aktuelle Zahl in den geprüften offiziellen Quellen nicht gefunden.",
    "need": "Starkes aktuelles Signal: Interpack 2026 mit neuer RoboSELEX-Roboterkollation und RoboAccess-Palettierung; 2025-Zertifikat belegt Design und Fertigung von Maschinen und robotischen Transportlinien.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Europäischen Einkaufsstandort bzw. Parma-Mechanikfertigung qualifizieren und mit Sonderteilen/Baugruppen für Robotik- und End-of-Line-Module ansetzen.",
    "sources": "https://www.sidel.com/en/about/media/press-releases/sidel-at-interpack-2026/ ; https://www.sidel.com/media/r3qb4wsw/0029395-ems-engus-ukas_14001.pdf ; https://www.sidel.com/",
    "date": "2026-08-04"
  },
  {
    "company": "SACMI Group / Packaging & Chocolate",
    "website": "https://sacmi.com/",
    "region": "Italien",
    "location": "Imola; Alba; Bologna; Mailand",
    "industry": "Verpackungsmaschinen, Lebensmitteltechnik, Industrieanlagen",
    "description": "Rund 5.200 Mitarbeitende weltweit laut offizieller Fachpack-2025-Mitteilung.",
    "need": "Starkes Signal: 2025 vorgestellte Verpackungsmaschinen mit bis zu 40 unabhängigen Antrieben, modularer Serienarchitektur sowie Pick-and-place-Robotik; mehrere europäische Produktionsstätten belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "89/100",
    "priority": "A",
    "next": "Einkauf der Packaging-&-Chocolate-Werke Alba/Bologna segmentieren; Sonderteile und Baugruppen für antriebsreiche Verpackungsmodule anbieten.",
    "sources": "https://sacmi.com/de-de/packaging/news/21733/sacmi-packaging-chocolate-at-fachpack-2025 ; https://sacmi.com/en-US/ipack-ima-2025 ; https://sacmi.com/en-US/las-vegas-2025",
    "date": "2026-08-04"
  },
  {
    "company": "pester pac automation GmbH",
    "website": "https://www.pester.com/",
    "region": "Deutschland",
    "location": "Wolfertschwenden",
    "industry": "Pharma- und Consumer-Verpackung, End-of-Line-Automation",
    "description": "Mehr als 1.000 Mitarbeitende weltweit laut offizieller Website.",
    "need": "Starkes aktuelles Signal: Interpack 2026 mit neuer Maschinenarchitektur; offizielle Historie nennt Ausbau und Modernisierung der eigenen Komponentenfertigung, ISO-Zertifikat Entwicklung, Produktion und Montage von Verpackungsmaschinen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Einkauf bzw. Komponentenfertigung in Wolfertschwenden prüfen; Spitzenlast-, Spezialteil- oder vormontierte Baugruppen als Nutzenhypothese testen.",
    "sources": "https://www.pester.com/ ; https://www.pester.com/en/company/pester-pac-automation/profile/ ; https://www.pester.com/med/pester-iso9001-en.pdf",
    "date": "2026-08-04"
  },
  {
    "company": "Harro Höfliger Verpackungsmaschinen GmbH",
    "website": "https://hoefliger.com/",
    "region": "Deutschland",
    "location": "Allmersbach im Tal; Backnang; Aspach; Satteldorf",
    "industry": "Pharma-/Medizintechnik-Produktions- und Verpackungsanlagen",
    "description": "2.500+ Mitarbeitende laut aktueller offizieller Unternehmensseite; 420 Mio. Euro Betriebsleistung 2024.",
    "need": "Starkes Signal: 2025/2026 belegter Ausbau des Verpackungsportfolios; Satteldorf begleitet Großprojekte von Konstruktion und Vormontage bis Linienintegration; strategische Partner werden ausdrücklich genannt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "93/100",
    "priority": "A",
    "next": "Satteldorf und zentrale Einkaufsorganisation getrennt prüfen; Einstieg über Großprojekte, Vormontage und kundenspezifische mechanische Baugruppen.",
    "sources": "https://hoefliger.com/en/about-us ; https://hoefliger.com/en/about-us/news/20-years-of-the-satteldorf-site ; https://hoefliger.com/en/products/consumer/packaging",
    "date": "2026-08-04"
  },
  {
    "company": "Romaco Group",
    "website": "https://www.romaco.com/",
    "region": "Deutschland",
    "location": "Karlsruhe, Köln, Steinen; Bologna; Barcelona",
    "industry": "Pharma-Verarbeitungs- und Verpackungsmaschinen",
    "description": "Mehr als 800 Mitarbeitende und sechs Produktionsstandorte laut offizieller Karriereseite.",
    "need": "Starkes aktuelles Signal: 2025 Lokalisierung der Formatteilproduktion und Ausbau mehrerer Produktions-/Experience-Standorte; neue Blistermaschinen mit Servo-Technik und Schnittstellen zu Kartonierer/Casepacker.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Karlsruher Einkauf und Formatteilorganisation qualifizieren; Sonder-/Formatteile sowie mechanische Baugruppen für Blister- und End-of-Line-Systeme fokussieren.",
    "sources": "https://www.romaco.com/career/who-we-are ; https://www.romaco.com/press-news/details/romaco-at-cphi-pmec-india-2025 ; https://www.romaco.com/press-news/details/romaco-at-pack-expo-in-las-vegas-usa",
    "date": "2026-08-04"
  },
  {
    "company": "Hugo Beck Maschinenbau GmbH & Co. KG",
    "website": "https://www.hugobeck.com/",
    "region": "Deutschland",
    "location": "Dettingen/Erms",
    "industry": "Verpackungsmaschinen, Automatisierung, Maschinenbau",
    "description": "Offizielle Website nennt 110 Fachkräfte im Maschinenbau, 20 Ingenieure und 100 Servicetechniker; damit Größenkriterium klar erfüllt.",
    "need": "Starkes aktuelles technisches Signal: neue paper-S-Bündelpackmaschine zur interpack 2026; offizielle Produktseite belegt kundenspezifische In-house-Projektierung und Fertigung sowie moderne Antriebs-/Steuerungstechnik. Keine Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Technischen Einkauf und Konstruktion in Dettingen qualifizieren; mit Sonderteilen, vormontierten Baugruppen und Antriebselementen für Zuführ-/Verpackungsachsen ansetzen.",
    "sources": "https://www.hugobeck.com/en/ ; https://www.hugobeck.com/en/solutions-portfolio/ ; https://www.hugobeck.com/en/company/newsroom/press-releases/hugo-beck-to-launch-new-sleeve-wrapper-for-sustainable-transport-packaging-at-interpack",
    "date": "2026-08-05"
  },
  {
    "company": "SN Maschinenbau GmbH",
    "website": "https://www.sn-packaging.com/",
    "region": "Deutschland",
    "location": "Wipperfürth",
    "industry": "Verpackungsmaschinen, Lebensmittel-/Pharma-/Kosmetiktechnik",
    "description": "Rund 300 Mitarbeitende am Standort laut offizieller Unternehmensseite; 2.500+ Maschinenprojekte.",
    "need": "Starkes aktuelles Signal: 2026 neue HSF 100 und FLH 300; offizielle Seite belegt Entwicklung, Konstruktion und Fertigung am Standort sowie hohe Fertigungstiefe. Konkrete Beschaffungsabsicht nicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Einkauf/Konstruktion in Wipperfürth prüfen; Nutzenhypothese für Spitzenlast-Sonderteile, Formatkomponenten und vormontierte mechanische Baugruppen testen.",
    "sources": "https://www.sn-packaging.com/en/company/sn/about-us ; https://www.sn-packaging.com/ ; https://www.packaging-labelling.com/pressreleases/packaging-know-how-and-film-expertise",
    "date": "2026-08-05"
  },
  {
    "company": "Uhlmann Pac-Systeme GmbH & Co. KG",
    "website": "https://www.uhlmann.de/",
    "region": "Deutschland",
    "location": "Laupheim",
    "industry": "Pharma-Verpackungsmaschinen, Automatisierung",
    "description": "Rund 2.600 Mitarbeitende weltweit laut aktueller offizieller Karriereseite; davon 1.700 in Laupheim (Basisjahr 2023).",
    "need": "Starkes aktuelles Signal: interpack 2026 mit neuen OEE-orientierten Lösungen und nachhaltigen Tray-Konzepten; offizieller Service nennt Ersatzteile, Formatteile, Upgrades und Modernisierung. Keine konkrete externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Einkauf und Formatteilorganisation in Laupheim qualifizieren; Sonder-/Formatteile und Baugruppen für Modernisierung und Lifecycle-Geschäft fokussieren.",
    "sources": "https://interpack.event.uhlmann.de/en/ ; https://sustainability.uhlmann.de/uhlmann-pac/es/career/apprenticeships-and-dual-study-courses ; https://www.uhlmann.de/en/products-and-solutions/customer-service-at-a-glance",
    "date": "2026-08-05"
  },
  {
    "company": "Bausch+Ströbel SE + Co. KG",
    "website": "https://www.bausch-stroebel.com/",
    "region": "Deutschland",
    "location": "Ilshofen",
    "industry": "Pharma-Maschinenbau, Abfüll- und Verpackungsanlagen",
    "description": "Über 3.000 Mitarbeitende weltweit, davon über 2.750 in Deutschland laut offizieller Unternehmenshistorie.",
    "need": "Starkes aktuelles Signal: interpack 2026 zeigt neue Anlagen-/Komponentenkonzepte; 2026 ausgezeichnete additive Fertigung für funktionsoptimierte pharmazeutische Komponenten und interne Weiterentwicklung seit 2020. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "89/100",
    "priority": "A",
    "next": "Einkauf/Engineering in Ilshofen qualifizieren; zunächst konventionell gefertigte Sonderteile und vormontierte Baugruppen außerhalb additiv optimierter Kernteile adressieren.",
    "sources": "https://www.bausch-stroebel.com/en/company/company/history/ ; https://www.bausch-stroebel.com/en/company/current/news-complete/additive-manufacturing ; https://www.bausch-stroebel.com/en/company/current/press",
    "date": "2026-08-05"
  },
  {
    "company": "BHS Corrugated Maschinen- und Anlagenbau GmbH",
    "website": "https://www.bhs-world.com/",
    "region": "Deutschland",
    "location": "Weiherhammer",
    "industry": "Wellpappenmaschinen, Automatisierung, Intralogistik, Anlagenbau",
    "description": "Mehr als 3.500 Mitarbeitende weltweit; 9 Produktionsstandorte und Niederlassungen in mehr als 20 Ländern laut offizieller Karriereseite.",
    "need": "Starkes aktuelles Signal: 2026 Einführung des neuen Slitter Scorer SR-C und NextGraphX; 2025 Einführung des intelligenten iBelt-Ersatzteilsystems. Das belegt laufende Komponenten- und Maschineninnovation, jedoch keine externe Beschaffungsabsicht.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Technischen Einkauf in Weiherhammer qualifizieren; mit Sonderteilen, vormontierten mechanischen Baugruppen und Antriebselementen für Corrugator-/Upgrade-Projekte ansetzen.",
    "sources": "https://www.bhs-world.com/en/news/product-news ; https://www.bhs-world.com/karriere/bhs-corrugated-360-grad/zahlen-storys ; https://www.bhs-world.com/en/corruverse",
    "date": "2026-08-05"
  },
  {
    "company": "FOCKE & CO. (GmbH & Co. KG) / FOCKE Gruppe",
    "website": "https://www.focke.com/",
    "region": "Deutschland",
    "location": "Verden (Aller); Barßel; Berlin",
    "industry": "Verpackungsmaschinen, Automatisierung, End-of-Line",
    "description": "2.200 Mitarbeitende, 350 Ingenieure und 5 Entwicklungsstandorte laut offizieller Unternehmensseite.",
    "need": "Starkes technisches Signal: aktuelle Smart Line und Hi5/Agility-Plattform mit modularen Konzepten und ausdrücklich fortschrittlicher Antriebs- bzw. Servo-Technik; Messe- und Produktaktivität 2026. Keine konkrete externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "89/100",
    "priority": "A",
    "next": "Einkaufs- und Konstruktionszuständigkeit in Verden bzw. Barßel trennen; Nutzenhypothese für Antriebselemente, Format-/Sonderteile und Baugruppen an konkreter Maschinenplattform testen.",
    "sources": "https://www.focke.com/ ; https://www.focke.com/cigarette-packaging-otp/ ; https://www.focke.com/cigarette-packaging-otp-v2/smart-line/ ; https://www.focke.com/hygiene-tissue-food-consumer/",
    "date": "2026-08-05"
  },
  {
    "company": "GEA Group Aktiengesellschaft / Food Processing & Packaging",
    "website": "https://www.gea.com/",
    "region": "Deutschland",
    "location": "Düsseldorf (Konzernsitz); relevante europäische Food-Processing- und Packaging-Standorte",
    "industry": "Lebensmittel- und Pharma-Maschinenbau, Verpackungstechnik, Prozessanlagen",
    "description": "Mehr als 18.000 Mitarbeitende und rund 5,5 Mrd. Euro Umsatz im Geschäftsjahr 2025 laut offizieller Pressemitteilung.",
    "need": "Starkes aktuelles Signal: Markteinführung des PowerPak 5000 zur interpack 2026, integriert mit OptiSlicer, OptiLoader und PowerLabel zu einer synchronisierten Linie bis 600 kg/h; mehrere weitere Maschinenneuheiten 2026. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Relevante deutsche/europäische Packaging-Einkaufseinheit und konkreten PowerPak-Fertigungsstandort ermitteln; erst danach gezielt mit Antriebselementen und Sonder-/Formatteilen ansprechen.",
    "sources": "https://www.gea.com/ja/news/trade-press/2026/powerpak-5000-thermoformer-launch/ ; https://www.gea.com/pt/events/interpack-2026/ ; https://www.gea.com/en/products/filling-packaging/",
    "date": "2026-08-05"
  },
  {
    "company": "groninger group / groninger & co. gmbh",
    "website": "https://www.groninger-group.com/",
    "region": "Deutschland",
    "location": "Crailsheim; Schnelldorf",
    "industry": "Pharma-, Kosmetik- und Consumer-Healthcare-Maschinenbau",
    "description": "Über 1.700 Mitarbeitende an drei Standorten und rund 300 Mio. Euro Gesamtleistung laut offizieller Unternehmensseite.",
    "need": "Sehr starkes aktuelles Signal: neue Montagehalle und Bürokomplex; beim Richtfest 2026 wurde der Ausbau mit zu klein gewordenen Bestandsflächen begründet. Zusätzlich nennt der Service Neubau von Formatteilen sowie Austausch spezifischer Komponenten. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "93/100",
    "priority": "A",
    "next": "Einkauf und Montage-/Formatteilorganisation in Crailsheim qualifizieren; Kapazitätsausbau als Anlass für Sonderteile und vormontierte mechanische Baugruppen nutzen.",
    "sources": "https://www.groninger-group.com/en/company/about-groninger/ ; https://www.groninger-group.com/en/news-downloads/press-releases/ ; https://www.groninger-group.com/en/services/service-portfolio/",
    "date": "2026-08-05"
  },
  {
    "company": "ROVEMA GmbH",
    "website": "https://www.rovema.com/",
    "region": "Deutschland",
    "location": "Fernwald",
    "industry": "Verpackungsmaschinen, Automatisierung, End-of-Line",
    "description": "Rund 650 Mitarbeitende laut aktueller offizieller Karriereseite.",
    "need": "Starkes aktuelles Signal: 2026 mehrere Markteinführungen, darunter BV Core 260 sowie ELD Flex und ETI-WA 443 mit schnellen Formatwechseln und hoher Kartonierleistung. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Einkaufs- und Konstruktionsverantwortung in Fernwald ermitteln; Ansprache an BV Core 260 und neue Endverpackungsmaschinen mit Fokus auf Antriebselemente, Format-/Sonderteile und Baugruppen ausrichten.",
    "sources": "https://www.rovema.com/en/company/newsroom/detail/ ; https://jobs.rovema.com/de?id=de8a00",
    "date": "2026-08-10"
  },
  {
    "company": "SOMIC Verpackungsmaschinen GmbH & Co. KG",
    "website": "https://www.somic-packaging.com/",
    "region": "Deutschland",
    "location": "Amerang; Teilefertigung Haag i. OB",
    "industry": "End-of-Line-Verpackungsmaschinen, Automatisierung",
    "description": "Über 600 Mitarbeitende weltweit laut offizieller Unternehmensseite.",
    "need": "Starkes aktuelles Signal: SOMIC stellte 2026 drei neue Maschinengenerationen vom Einstiegs- bis zum Hochleistungssegment vor; die SOMIC 202 verarbeitet Kartons mit kettengeführtem Zuschnitttransport. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Beschaffung zwischen Amerang und Teilefertigung Haag abgrenzen; mögliche Fremdvergabe für Spitzenlast, Sonderteile und vormontierte mechanische Einheiten prüfen.",
    "sources": "https://apac.somic-packaging.com/company/news/somic-at-interpack-2026/ ; https://www.somic-packaging.com/en/company/about-somic/",
    "date": "2026-08-10"
  },
  {
    "company": "Körber Pharma Packaging AG / Körber Business Area Pharma",
    "website": "https://www.koerber-pharma.com/",
    "region": "Schweiz",
    "location": "Grabs; relevante Maschinenstandorte Markt Schwaben und Pécs",
    "industry": "Pharma-Verpackungsmaschinen, Inspektion, Handling und Automatisierung",
    "description": "Über 250 Mitarbeitende am Standort Grabs; Campus Pécs mit Arbeitsplätzen für 970 Beschäftigte laut offiziellen Standortseiten.",
    "need": "Sehr starkes aktuelles Signal: zwei Maschinenstarts zur interpack 2026; zusätzlich bündelt der Campus Pécs Konstruktion, Zerspanung, Blechbearbeitung, Montage und Supply Chain bei hoher Nachfrage und steigenden Aufträgen. Keine konkrete externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "94/100",
    "priority": "A",
    "next": "Beschaffungszuständigkeit für ALVA/SPE6-P2 und zwischen Grabs, Markt Schwaben und Pécs klären; Supplier- und Make-or-buy-Prüfung mit Fokus auf Sonderteile und Baugruppen priorisieren.",
    "sources": "https://service.koerber-pharma.com/interpack-2026 ; https://www.koerber-pharma.com/en/about-us/locations ; https://www.koerber-pharma.com/en/blog/a-state-of-the-art-production-facility-in-the-heart-of-europe",
    "date": "2026-08-10"
  },
  {
    "company": "Herbold Meckesheim GmbH / Coperion Recycling",
    "website": "https://www.coperion.com/",
    "region": "Deutschland",
    "location": "Meckesheim",
    "industry": "Recyclingmaschinen, Anlagenbau, Förder- und Verfahrenstechnik",
    "description": "Mehr als 230 Mitarbeitende am Hauptsitz Meckesheim laut offizieller Pressemitteilung.",
    "need": "Sehr starkes aktuelles Signal: konkreter Folgeauftrag 2026 für eine zweite PET-Waschlinie, aktuell in Auslieferung und Inbetriebnahme; enthält optimierte Prozessmodule, Debaler und kombinierte Nass-/Trocken-Waschtrommel. Keine Aussage über externe Komponentenbeschaffung.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Projekt- und Komponentenbeschaffung in Meckesheim für Recyclinglinien qualifizieren; mit konkretem Bezug auf Zuführung, Waschtrommel, Sonderteile und vormontierte Einheiten ansprechen.",
    "sources": "https://coperion.com/media/hqddig3q/herbold_doga_washingline_en.pdf ; https://www.coperion.com/de/unternehmen/ueber-coperion",
    "date": "2026-08-10"
  },
  {
    "company": "KHS GmbH / KHS Group",
    "website": "https://www.khs.com/",
    "region": "Deutschland",
    "location": "Dortmund; Bad Kreuznach; Kleve; Worms; Hamburg (rund 450 Mitarbeitende)",
    "industry": "Abfüll- und Verpackungsmaschinen, Anlagenbau, Automatisierung",
    "description": "5.769 Mitarbeitende gruppenweit 2025; rund 450 Mitarbeitende am Produktionsstandort Hamburg laut offizieller Standortseite.",
    "need": "Starkes aktuelles Signal: 2026 neue BottleClip-Anwendung und breites Retrofit-Programm; am Standort Hamburg neue Generation der InnoPET-Blomax-Streckblasmaschinen sowie aktuelle FreshSafe-Block-Technik. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Beschaffungszuständigkeit des Hamburger Werks für InnoPET-Technik klären; Ansatz über verschleiß-/formatabhängige Sonderteile, Antriebselemente und vormontierte Einheiten testen.",
    "sources": "https://www.khs.com/en/company/news/press-releases/detail/from-the-packaging-to-the-line ; https://www.khs.com/en/company/news/press-releases/detail/future-proof-with-the-khs-conversion-catalog ; https://www.khs.com/en/company/about-us ; https://www.khs.com/unternehmen/aktuelles/pressemitteilungen/detail/jubilaeum-bei-khs-hamburg-50-jahre-pionierarbeit-und-ein-starkes-team-fuer-die-zukunft ; https://www.khs.com/fileadmin/user_upload/InnoPET_FreshSafe_Block_mit_Plasmax_20Q.pdf",
    "date": "2026-08-10"
  },
  {
    "company": "AMF-Bruns GmbH & Co. KG",
    "website": "https://amf-foerderanlagen.de/",
    "region": "Deutschland",
    "location": "Apen",
    "industry": "Fördertechnik, Maschinen- und Anlagenbau",
    "description": "Rund 350 Mitarbeitende am Standort Apen und weitere rund 100 in der Unternehmensgruppe laut offizieller Unternehmensgeschichte.",
    "need": "Starkes aktuelles Signal: AMF-Bruns meldete 2025 den größten Einzelauftrag der Unternehmensgeschichte im Förderanlagenbereich mit knapp 15 Mio. Euro und leitete die Anschaffung einer neuen Laseranlage ein. Das deutet auf hohe Projekt- und Fertigungsaktivität, belegt aber keine externe Beschaffungsabsicht.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Beschaffung für laufende Förderanlagenprojekte und Kapazitätsspitzen qualifizieren; Einstieg über projektspezifische Sonderteile, Antriebselemente und vormontierte mechanische Einheiten.",
    "sources": "https://amf-foerderanlagen.de/geschichte/ ; https://amf-foerderanlagen.de/wp-content/uploads/2025/08/25-0020_AMF_TeAMForum_01-2025.pdf ; https://amf-foerderanlagen.de/en/continuous-conveyors/",
    "date": "2026-08-10"
  },
  {
    "company": "SCHULZ Systemtechnik GmbH",
    "website": "https://schulz.st/",
    "region": "Deutschland",
    "location": "Visbek; Bremen",
    "industry": "Automatisierung, Robotik, Sondermaschinenbau",
    "description": "Mehr als 1.100 Mitarbeitende an 14 Standorten laut offizieller Unternehmensseite.",
    "need": "Starkes aktuelles Signal: 2026 veröffentlichte SCHULZ eine modulare hochautomatisierte Sondermaschine mit 6-Achs-Roboter, Zuführung, Bearbeitung, Prüfung und Tray-Verpackung. Zusätzlich wurde ein Großprojekt mit 34 Robotern und Schubplattformkreislauf umgesetzt. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Mechanische Fremdvergabe am Standort Bremen prüfen; mit Bezug auf modulare Sondermaschinen, Greifer-/Vorrichtungsteile und vormontierte Baugruppen ansprechen.",
    "sources": "https://schulz.st/unternehmen/ ; https://schulz.st/automatisierungsloesung-fuer-outsert-technologie/ ; https://schulz.st/nur-roboter-sind-schneller/",
    "date": "2026-08-10"
  },
  {
    "company": "OAS AG",
    "website": "https://www.oas.de/",
    "region": "Deutschland",
    "location": "Bremen",
    "industry": "Anlagenbau, Förder-, Dosier- und Automatisierungstechnik",
    "description": "Mehr als 240 Mitarbeitende an vier Standorten laut aktueller offizieller Karrierebroschüre.",
    "need": "Starkes aktuelles Signal: OAS meldete 2025 ein konkretes Projekt für ein Tanklager samt Förderanlage, Engineering, Automatisierung und Montage. Eine Leistungsübersicht von 2025 nennt Fertigung und kundenspezifisch angepasste modulare Einheiten. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "83/100",
    "priority": "A",
    "next": "Zentralen technischen Einkauf und selbst beschaffte mechanische Materialgruppen klären; Einstieg über Förder-/Dosiermodule und projektspezifische Sonderteile.",
    "sources": "https://www.oas.de/fileadmin/user_upload/OAS_AG/Downloads/OAS_Bewerberbroschuere_DE.pdf ; https://www.oas.de/anlagenbau ; https://www.oas.de/neuigkeit/tanklager-und-foerderanlage-fuer-global-taetigen-baustoffproduzenten ; https://www.oas.de/fileadmin/user_upload/OAS_AG/Downloads/OAS_PRO16_Kompetenz_im_Anlagenbau-DE_web.pdf",
    "date": "2026-08-10"
  },
  {
    "company": "STILL GmbH",
    "website": "https://www.still.de/",
    "region": "Deutschland",
    "location": "Hamburg",
    "industry": "Intralogistik, Flurförderzeuge, mobile Robotik",
    "description": "Rund 7.100 Mitarbeitende weltweit laut offizieller Unternehmensinformation 2026; Hauptsitz und bedeutender Produktionsstandort Hamburg.",
    "need": "Starkes aktuelles Signal: STILL industrialisierte 2025 mehrere automatisierte Serienfahrzeuge auf Basis modularer standardisierter Komponenten. 2026 folgte eine automatisierte Tiefkühllösung mit Hochhubwagen und Paletten-Shuttle-System mit 3.700 Stellplätzen. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "81/100",
    "priority": "A",
    "next": "Zuständige Warengruppe für mechanische Komponenten der iGo-Fahrzeuge und Shuttle-Systeme ermitteln; Lieferantenqualifizierung und Make-or-buy prüfen.",
    "sources": "https://www.still.de/unternehmen.html ; https://data.still.de/assets/products/News/2026/Global/Pre-Report_LogiMAT_2026/DE_STILL_Pressemitteilung_Vorbericht_LogiMAT_2026.pdf?download=1 ; https://www.still.de/unternehmen/news-presse/news/detail/skalierbar-verfuegbar-industrialisiert-still-praesentiert-smartes-automatisierungsportfolio-fuer-jedes-einsatzszenario.html ; https://www.still.de/unternehmen/news-presse/news/detail/eine-vollautomatisierte-tiefkuehllogistik-fuer-das-block-logistik-fertigwarenlager.html",
    "date": "2026-08-10"
  },
  {
    "company": "Güdel Group AG",
    "website": "https://www.gudel.com/",
    "region": "Schweiz",
    "location": "Langenthal",
    "industry": "Automatisierung, Robotik, Maschinenbau",
    "description": "Rund 1.000 Mitarbeitende weltweit an über 20 Standorten laut offizieller Unternehmensseite.",
    "need": "Starkes technisches Signal: Güdel entwickelt und fertigt in Langenthal Linear- und Antriebskomponenten sowie kundenspezifische Portalrobotik; aktuelle Karriere- und Unternehmensseiten nennen Wachstum und laufende Rekrutierung. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Make-or-buy und relevante mechanische Warengruppen in Langenthal klären; Ansatz über Sonderteile und vormontierte Einheiten für Portal- und Robotiksysteme.",
    "sources": "https://www.gudel.com/company/about-guedel ; https://de.gudel.com/unternehmen/jobs-berufsbildung/jobs ; https://media.gudel.com/v/iOBqgR9k/",
    "date": "2026-08-11"
  },
  {
    "company": "Stäubli International AG / Robotics",
    "website": "https://www.staubli.com/",
    "region": "Schweiz",
    "location": "Pfäffikon SZ; Robotikproduktion u. a. Faverges, Frankreich",
    "industry": "Robotik, Mechatronik, Automatisierung",
    "description": "6.000 Mitarbeitende weltweit laut offizieller Stäubli-Mitteilung 2025.",
    "need": "Starkes aktuelles Signal: Stäubli baut die nächste Robotergeneration auf und besetzt dafür Produktmanagement- und Entwicklungsrollen; das Portfolio umfasst neue Industrie- und mobile Robotik. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "89/100",
    "priority": "A",
    "next": "Beschaffungs- und Fertigungsverantwortung der Robotics Division zwischen Pfäffikon und Faverges klären; danach mechanische Sonderteile/Baugruppen gezielt prüfen.",
    "sources": "https://www.staubli.com/global/de/news/global/2025/staeubli-robotics-executive-president-ernennung.html ; https://www.staubli.com/ch/de/robotics/produkte.html ; https://www.staubli.com/ch/fr/carriere/detail-du-poste.job-744000118151877.html",
    "date": "2026-08-11"
  },
  {
    "company": "Interroll Holding AG / Interroll Group",
    "website": "https://www.interroll.com/",
    "region": "Schweiz",
    "location": "Sant'Antonino",
    "industry": "Fördertechnik, Intralogistik, Sortiertechnik",
    "description": "Durchschnittlich 2.379 FTE im Jahr 2025 laut offiziellem Geschäftsbericht.",
    "need": "Sehr starkes aktuelles Signal: 2025 stieg der Auftragseingang auf 545,3 Mio. CHF; 2026 erweitert Interroll die Sorting Solutions Platform und führt die prämierte MCP PLAY Plattform weiter. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "94/100",
    "priority": "A",
    "next": "Einkaufswarengruppen und Fertigungsstandorte für Conveyors & Sorters identifizieren; mechanische Sonderteile und vormontierte Module priorisieren.",
    "sources": "https://investors.interroll.com/reporting/annual-report-2025/financial-report ; https://investors.interroll.com/reporting/annual-report-2025/quick-report ; https://www.interroll.com/fileadmin/user_upload/LogiMAT-Press_release_FINAL_25.03.26_ENG.pdf",
    "date": "2026-08-11"
  },
  {
    "company": "Ferag AG / Ferag Solutions",
    "website": "https://www.ferag.com/",
    "region": "Schweiz",
    "location": "Hinwil",
    "industry": "Intralogistik, Förder- und Sortiertechnik, Automation",
    "description": "Mehr als 250 Mitarbeitende weltweit laut offizieller Ferag-Solutions-Seite.",
    "need": "Starkes aktuelles Signal: Seit Januar 2025 ist Ferag Solutions eigenständig auf Intralogistik fokussiert und treibt mit eigener Technologies-Division Produktentwicklung und internationale Projekte voran. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "88/100",
    "priority": "A",
    "next": "Eigenständige Einkaufsstruktur von Ferag Solutions in Hinwil qualifizieren; Einstieg über projektbezogene Sonderteile und Baugruppen für skyfall/denisort.",
    "sources": "https://ferag.com/en/company/about-us/ ; https://www.ferag.com/labor-trends-and-workforce-shortage-in-intralogistics-automation-as-the-solution/",
    "date": "2026-08-11"
  },
  {
    "company": "GEBHARDT Intralogistics Group",
    "website": "https://gebhardt-group.com/",
    "region": "Deutschland",
    "location": "Sinsheim",
    "industry": "Intralogistik, Fördertechnik, Lagerautomation",
    "description": "Rund 500 Mitarbeitende laut offizieller GEBHARDT-Unternehmensdarstellung.",
    "need": "Sehr starkes aktuelles Signal: 2026 erweitert GEBHARDT sein Angebot durch die Übernahme der AKDV GmbH, eröffnet einen Standort in Paris und zeigt neue Smart-Intralogistics-Lösungen; zudem wurde ein neues Ersatzteillager bei DIEFFENBACHER automatisiert.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "93/100",
    "priority": "A",
    "next": "Einkaufsverantwortung in Sinsheim und Warengruppen für Sortier-/Fördermodule ermitteln; mit konkretem Projekt- und Baugruppenbezug ansprechen.",
    "sources": "https://gebhardt-group.com/en/ ; https://marketing.gebhardt-group.com/en/gebhardt-sorting-solutions-the-guide",
    "date": "2026-08-11"
  },
  {
    "company": "Jungheinrich AG",
    "website": "https://www.jungheinrich.com/",
    "region": "Deutschland",
    "location": "Hamburg; Moosburg und weitere Werke",
    "industry": "Intralogistik, Lagerautomation, mobile Robotik",
    "description": "21.438 Mitarbeitende Ende 2025 laut offiziellem Geschäftsbericht.",
    "need": "Sehr starkes aktuelles Signal: 2025 stiegen Auftragseingang und Umsatz; das Automationsportfolio wurde erweitert. In Moosburg entsteht bis Ende 2026 ein Experience Center mit 1.700 m² Materialflussarena und Platz für bis zu 400 Beschäftigte im Segment Automation & Warehouse Equipment.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Zuständige Commodity- und Standortbeschaffung für Automation & Warehouse Equipment in Moosburg identifizieren; Lieferantenqualifizierung prüfen.",
    "sources": "https://www.jungheinrich.com/en/investor-relations/annual-report-2025 ; https://www.jungheinrich.com/en/newsroom/jungheinrich-blog/this-is-what-the-jec-in-moosburg-will-look-like-2370554 ; https://www.jungheinrich.com/en/about-us/we-are-shaping-the-warehouse-of-the-future-1616980",
    "date": "2026-08-11"
  },
  {
    "company": "STIWA Group / STIWA Automation",
    "website": "https://www.stiwa.com/",
    "region": "Österreich",
    "location": "Attnang-Puchheim",
    "industry": "Hochleistungsautomation, Sondermaschinenbau, Fertigung",
    "description": "Über 2.200 Mitarbeitende gruppenweit; mehr als 1.000 im Bereich Automation laut offiziellen STIWA-Quellen.",
    "need": "Sehr starkes aktuelles Signal: STIWA präsentiert 2026 integrierte Batterieproduktionslösungen und plant ab 2027 Serienkapazität von über 60 Mio. Komponenten jährlich; mehr als 60 Maschinen pro Jahr und hohe Fertigungstiefe sind offiziell ausgewiesen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "95/100",
    "priority": "A",
    "next": "Einkauf für STIWA Automation und Batterieprojekte qualifizieren; Kapazitätsspitzen, Sonderteile und vormontierte Einheiten als Einstieg prüfen.",
    "sources": "https://www.stiwa.com/en/automation/industries ; https://www.stiwa.com/en/automation/battery-show-2026 ; https://www.stiwa.com/en/company/business-units ; https://www.stiwa.com/fileadmin/user_upload/aws_jobs_pdf/47262_en.pdf",
    "date": "2026-08-11"
  },
  {
    "company": "IMA Schelling Group GmbH / IMA Schelling Austria GmbH",
    "website": "https://www.imaschelling.com/",
    "region": "Österreich",
    "location": "Schwarzach; Lübbecke",
    "industry": "Maschinenbau, Lagerautomation, Förder- und Handhabungstechnik",
    "description": "1.966 Mitarbeitende weltweit; 500 am Standort Schwarzach laut offizieller Unternehmensseite.",
    "need": "Starkes aktuelles Signal: Zum 10-jährigen Gruppenjubiläum 2025 meldete IMA Schelling Wachstum auf 1.960 Mitarbeitende und 395 Mio. Euro Umsatz sowie zusätzliche R&D-Ressourcen; aktuelle Lösungen verbinden Lager, Handling, Fördern und Robotik.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Beschaffungsaufteilung zwischen Schwarzach und Lübbecke klären; Einstieg über projektbezogene Sonderteile, Achskomponenten und Baugruppen.",
    "sources": "https://www.imaschelling.com/en/ima-schelling-group/company/about-us ; https://www.imaschelling.com/en/ima-schelling-group/company/locations/austria ; https://www.imaschelling.com/en/ima-schelling-group/latest-news/news/items/why-1-plus-1-equals-10",
    "date": "2026-08-11"
  },
  {
    "company": "KASTO Maschinenbau GmbH & Co. KG",
    "website": "https://www.kasto.com/",
    "region": "Deutschland",
    "location": "Achern; Schalkau",
    "industry": "Maschinenbau, Lagertechnik, Materialhandling, Automation",
    "description": "Größe über mehrere Standorte und internationale Gesellschaften klar über 50; exakte aktuelle Mitarbeiterzahl auf offizieller Website nicht gefunden.",
    "need": "Starkes aktuelles Signal: 2026 führt KASTO ProControl, KASTOcenter compact und eine neue KASTOssb-Generation ein; mehrere neue Referenzen zeigen hochautomatisierte Produktionslogistik und Materialflusslösungen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "82/100",
    "priority": "B",
    "next": "Aktuelle Beschäftigtenzahl und Einkaufsstruktur in Achern nachprüfen; danach Sonderteile/Baugruppen für Lager- und Materialhandlingachsen adressieren.",
    "sources": "https://www.kasto.com/en/company/news ; https://www.kasto.com/en/contact/exhibitions-and-conferences/amb ; https://www.kasto.com/en/storage/buffer-storage",
    "date": "2026-08-11"
  },
  {
    "company": "Fill Gesellschaft m.b.H.",
    "website": "https://www.fill.co.at/",
    "region": "Österreich",
    "location": "Gurten",
    "industry": "Sondermaschinenbau, Automation, Produktionsanlagen",
    "description": "1.000 Mitarbeitende und 202,5 Mio. Euro Betriebsleistung 2024 laut offizieller Unternehmensseite.",
    "need": "Starkes aktuelles Signal: Fill wurde 2026 als innovativstes Unternehmen Österreichs hervorgehoben; aktuelle Unterlagen zeigen hochautomatisierte Aerospace- und Plattenfertigungsanlagen sowie fortlaufende Projekt- und Arbeitsvorbereitungsrekrutierung.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "90/100",
    "priority": "A",
    "next": "Technischen Einkauf und Arbeitsvorbereitung in Gurten qualifizieren; projektbezogene Sonderteile, Antriebselemente und vormontierte Einheiten prüfen.",
    "sources": "https://www.fill.co.at/en/company/look-for-meaning-and-you-will-find-purpose ; https://www.fill.co.at/de ; https://www.fill.co.at/Downloads/KC%20Folder/Folder%20Aerospace%20Manufacturing%20Systems.pdf ; https://www.fill.co.at/en/career/discover-your-job-at-fill/project-disponent-for-work-preparation-m-f-x",
    "date": "2026-08-11"
  }
];
