window.LEADS = [
  {
    "company": "F.EE GmbH / F.EE-Unternehmensgruppe",
    "website": "https://www.fee.de/",
    "region": "Deutschland / Bayern",
    "location": "Neunburg vorm Wald; weitere Niederlassungen u. a. Frankfurt und Leipzig",
    "industry": "Automatisierungstechnik, Maschinenbau, Robotik",
    "description": "Industrieautomation mit Geschäftsbereichen Elektrotech Engineering, Automation Robotik, Informatik + Systeme und Energietechnik; Maschinenbau-Sparte mit Robotik, Fördertechnik, Linearachsen und Sondervorrichtungen.",
    "need": "Mittleres bis starkes technisches Signal: F.EE bietet Universal-Verfahrachsen/Linearachsen für Roboter, Fördertechnik, Drehtische/Antriebe sowie Sondermaschinenbau und eigene Einzel-/Serienfertigung an. Das spricht für Bedarf an mechanischen Antriebselementen, Sonderteilen und Baugruppen, ohne aktuelle Beschaffungsabsicht zu belegen.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Linear-/Förderachsen als Prüfpunkt; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "86/100 - A-Lead: sehr guter Zielbranchenfit, klare technische Produktnähe, Größe gut belegt; Bedarf ist technische Vertriebsannahme, keine belegte Einkaufsabsicht.",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung: passenden Einstieg über technischen Einkauf oder Leitung Maschinenbau/Robotik recherchieren; mit konkretem Bezug auf Linearachsen/Fördertechnik und Sonderteile ansprechen.",
    "sources": "https://www.fee.de/ ; https://www.fee.de/unternehmen/zahlen-fakten ; https://www.ausbildungsoffensive-bayern.de/mitgliedsunternehmen/profile/fee-industrieautomation-gmbh-u-co-kg-92431-neunburg-vorm-wald/",
    "date": "2026-07-31"
  },
  {
    "company": "ASS Maschinenbau GmbH",
    "website": "https://www.ass-automation.com/",
    "region": "Deutschland / Nordrhein-Westfalen",
    "location": "Overath",
    "industry": "Robotik, Greifertechnik, Automatisierung, Maschinenbau",
    "description": "Hersteller von Greiferteilen, Roboterhänden/EOAT, Automationsanlagen und Sonder-Greiferteilen für Spritzguss, Automatisierung, Automotive/E-Mobilität und Kunststoffindustrie.",
    "need": "Mittleres technisches Signal: umfangreicher mechatronischer Komponentenbau, kundenspezifische Greiflösungen und Turn-Key-Automationsanlagen deuten auf Bedarf an Sonderteilen, mechanischen Baugruppen und Antriebskomponenten hin; keine konkrete Beschaffungsabsicht belegt.",
    "fit": "CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Antriebstechnik bei Automationsanlagen als Prüfpunkt; Zahnriemen/Zahnriemenscheiben nur indirekter Fit",
    "relevance": "78/100 - B-Lead: guter Robotik- und Baugruppenfit mit belegter Größe; konkreter Zahnriemen-/Antriebseinsatz nicht direkt belegt.",
    "priority": "B",
    "next": "Vor Ansprache technische Produkt-/Katalogtiefe prüfen; Einstieg über Sonderteile/Baugruppen für Greifer- und Automationsanlagen wählen.",
    "sources": "https://www.ass-automation.com/de/unternehmen/ass-maschinenbau-gmbh.html",
    "date": "2026-07-31"
  },
  {
    "company": "A+F Automation + Fördertechnik GmbH / EOL Group",
    "website": "https://eol.group/de/unternehmen/af-automationfoerdertechnik",
    "region": "Deutschland / Nordrhein-Westfalen",
    "location": "Kirchlengern",
    "industry": "Verpackungsmaschinen, Fördertechnik, End-of-Line-Automation",
    "description": "Hersteller von Endverpackungsmaschinen und integrierten Verpackungslösungen; Portfolio umfasst Pick & Place Packer, Palettierer, Umpacker und Aufrichter für Lebensmittel-, Getränke-, Kosmetik- und Pharmaanwendungen.",
    "need": "Mittleres technisches Signal: individuelle Endverpackungs- und Palettieranlagen mit Pick-and-place, Robotik und Transportsystemen legen Bedarf an Antriebselementen, Förder-/Positionierkomponenten und Sonderbaugruppen nahe; aktuelle Beschaffungsabsicht nicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Förder-/Positionieraufgaben als Prüfpunkt; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "82/100 - A-Lead: sehr guter Fit zu Verpackungsmaschinen/Fördertechnik und klare Anwendungen; Mitarbeiterzahl für A+F teilweise aus LinkedIn/CGS ergänzend belegt.",
    "priority": "A",
    "next": "Vertriebsprüfung mit Fokus auf Ersatz-/Sonderteile, Fördertechnik-Komponenten und Baugruppen für End-of-Line-Anlagen; Lieferanten-/Einkaufsstruktur der EOL Group klären.",
    "sources": "https://eol.group/de/unternehmen/af-automationfoerdertechnik ; https://www.wlw.de/de/firma/af-automation-foerdertechnik-gmbh-344825 ; https://www.cgs-management.com/en/portfolio/eol-packaging-experts",
    "date": "2026-07-31"
  },
  {
    "company": "DFT - Dürkopp Fördertechnik GmbH",
    "website": "https://www.duerkopp.com/de/",
    "region": "Deutschland / Ostwestfalen-Lippe",
    "location": "Bielefeld",
    "industry": "Intralogistik, Fördertechnik, Anlagenbau, Automatisierungsanlagen",
    "description": "Weltweit agierender Lösungsanbieter für automatisierte Sortier- und Fördertechnik im Anlagenbau der Intralogistik; Teil der KNAPP-Gruppe.",
    "need": "Starkes technisches Signal: offizielle DFT-/OWL-Quellen belegen automatisierte Sortier- und Fördertechnik, Hängefördertechnik und Anlagenbau für Intralogistik. Laufende Jobs/Projektplanung deuten auf Angebotslayouts und Materiallisten für Projekte hin. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Förder-/Sortiermodule; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "88/100 - A-Lead: sehr starker Branchen- und Komponentenfit, Größe gut belegt, konkrete Förder-/Sortiertechnik; Konzernzugehörigkeit als Zugangshürde.",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung mit Fokus auf mechanische Antriebselemente und Sonder-/Baugruppen für Sortier- und Hängefördermodule; Einkaufsweg über DFT vs. KNAPP klären.",
    "sources": "https://www.duerkopp.com/de/ ; https://www.owl-maschinenbau.de/unternehmen/dft-duerkopp-foerdertechnik-gmbh/ ; https://de.linkedin.com/company/dft-duerkopp ; https://haystackapp.io/jobs/5675456f-bde8-4928-b053-120eff8aaa65",
    "date": "2026-07-31"
  },
  {
    "company": "MINDA Industrieanlagen GmbH",
    "website": "https://www.minda.com/de/",
    "region": "Deutschland / Ostwestfalen-Lippe",
    "location": "Minden",
    "industry": "Anlagenbau, Intralogistik, Fördertechnik",
    "description": "Spezialist für kundenspezifische Intralogistiksysteme, Transportanlagen und Logistiksysteme für Wellpappe, Vollkarton, Papier, Massivholz und Stückgüter.",
    "need": "Starkes technisches Signal: offizielle Quellen belegen kundenspezifische Fördertechnik und Intralogistiksysteme; Stadt Minden bestätigt Entwicklung und Produktion am Standort. Forbo-Fallbeispiel nennt Spezialanlagenbau und interne Materialflusslösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Förder-/Positioniertechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "86/100 - A-Lead: sehr guter Fit zu Fördertechnik/Intralogistik, kundenspezifische Anlagen und Produktion belegt; Bedarf bleibt technische Vertriebsannahme.",
    "priority": "A",
    "next": "Ansprache auf Sonderteile/Baugruppen und Antriebskomponenten für kundenspezifische Förder-/Transportanlagen vorbereiten; Einkaufs-/Konstruktionsrollen recherchieren.",
    "sources": "https://www.minda.com/de/ ; https://www.minda.com/en/ ; https://www.owl-maschinenbau.de/unternehmen/minda-industrieanlagen-gmbh/ ; https://www.minden.de/wirtschaft-mobilitaet-wohnen/standort-minden/arbeiten-in-minden/minda/ ; https://www.forbo.com/movement/en-gl/about-us/winning-solutions/minda-industrieanlagen-gmbh/p4qqvm",
    "date": "2026-07-31"
  },
  {
    "company": "GHD Georg Hartmann Maschinenbau GmbH",
    "website": "https://www.ghd.net/de/startseite",
    "region": "Deutschland / Ostwestfalen-Lippe",
    "location": "Delbrück",
    "industry": "Maschinenbau, Lebensmittel- und Verpackungsmaschinen",
    "description": "Hersteller technologisch hochentwickelter Maschinen und Anlagen zum Schneiden und Verpacken von Backwaren und Lebensmitteln.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Produktseite nennt komplette Maschinen/Anlagen zum Schneiden und Verpacken; Messeprofile bestätigen führende Rolle in Schneide-/Verpackungsmaschinen. Das legt Bedarf an Sonderteilen, Baugruppen und Antriebselementen nahe. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Verpackungs-/Transport-/Schneidachsen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "80/100 - A-Lead: klarer Verpackungsmaschinenfit und bestätigte Größenklasse; konkreter Komponenten-/Antriebseinsatz nicht direkt dokumentiert.",
    "priority": "A",
    "next": "Vor Ansprache technische Produkt-/Ersatzteilinformationen prüfen; Einstieg über Sonderteile/Baugruppen für Schneide- und Verpackungsanlagen.",
    "sources": "https://www.ghd.net/de/startseite ; https://de.linkedin.com/company/ghd-georg-hartmann-maschinenbau-gmbh ; https://www.iba-tradefair.com/en/discover/all-exhibitors-and-suppliers/ghd-georg-hartmann-maschinenbau-gmbh ; https://www.interpack.com/vis/v1/en/exhprofiles/BSN93PqHQUyR4I82jEZNjQ",
    "date": "2026-07-31"
  },
  {
    "company": "HAVER & BOECKER OHG / Machinery Division",
    "website": "https://www.haverboecker.com/de/",
    "region": "Deutschland / Ostwestfalen-Lippe / angrenzendes Westfalen",
    "location": "Oelde",
    "industry": "Verpackungstechnologie, Maschinenbau, Anlagenbau",
    "description": "Familienunternehmen mit Drahtgewebeprodukten und Verpackungstechnologie; Machinery Division entwickelt, produziert und vermarktet Systeme und Anlagen für Füllen, Wiegen und Verarbeiten von Schüttgütern.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Seite belegt individuelle Maschinenlösungen und Verpackungstechnologie; Machinery-Division-Profile belegen Entwicklung und Produktion von Systemen/Anlagen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemen/Zahnriemenscheiben als Prüfpunkt bei Förder-/Dosier-/Verpackungsachsen",
    "relevance": "79/100 - B-Lead: sehr starker Maschinen-/Verpackungsfit und Größe; Standort knapp außerhalb enger OWL-Kernregion und Konzern-/Division-Struktur klären.",
    "priority": "B",
    "next": "Als strategischen Prüflead aufnehmen; spezifische Einkaufs-/Konstruktionskontakte der Machinery Division und Lieferantenanforderungen recherchieren.",
    "sources": "https://www.haverboecker.com/de/ ; https://be.linkedin.com/company/haver-boecker-machinery-division ; https://www.at-minerals.com/en/artikel/at_HAVER_BOECKER_Machinery_Division-3323544.html",
    "date": "2026-07-31"
  },
  {
    "company": "Lödige Industries GmbH",
    "website": "https://www.lodige.com/de-de/",
    "region": "Deutschland / Ostwestfalen-Lippe",
    "location": "Warburg/Scherfede; Paderborn",
    "industry": "Fördertechnik, Intralogistik, Logistiksysteme, Materialflusslösungen",
    "description": "Spezialist für Logistiksysteme, Aufzugsanlagen und kundenspezifische Materialflusslösungen; deutsche Standorte u. a. Paderborn und Warburg/Scherfede.",
    "need": "Starkes technisches Signal: offizielle Seite belegt kundenspezifische Materialflusslösungen und Heavy-Goods-Movement; deutsche Standortseite nennt Fördertechnik und Produktionslogistik. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Förder-/Materialflussmodule",
    "relevance": "82/100 - A-Lead: sehr guter Fördertechnik-/Materialflussfit, Größe und Standorte belegt; Beschaffungsstruktur vermutlich zentral/konzernartig zu prüfen.",
    "priority": "A",
    "next": "Vertriebsprüfung auf Produktionslogistik-/Fördertechnikkomponenten; passende Rollen am Standort Paderborn/Warburg und zentrale Einkaufsstruktur identifizieren.",
    "sources": "https://www.lodige.com/en-global/ ; https://www.lodige.com/de-de/unternehmen/wo-sie-uns-finden/deutschland/ ; https://de.linkedin.com/company/lodige-industries",
    "date": "2026-07-31"
  },
  {
    "company": "Vanderlande Industries B.V.",
    "website": "https://www.vanderlande.com/",
    "region": "Niederlande",
    "location": "Veghel",
    "industry": "Intralogistik, Fördertechnik, Logistikprozess-Automation, Anlagenbau",
    "description": "Globaler Anbieter für Logistikprozess-Automation in Airports, Warehousing und Parcel; Portfolio mit integrierten Systemen, Software und Lifecycle Services.",
    "need": "Starkes technisches Signal: offizielle Website nennt integrierte Logistikautomationssysteme; Karrierequelle nennt 3D-Conveyor-Modelle, mechanische Layouts, Schnittstellen zu Equipment und Procurement; FY2025-Bericht belegt Design/Implementation von logistischen Automationslösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Förder-/Sortiermodule; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung.",
    "relevance": "92/100 - A-Lead: sehr starker Zielbranchenfit, große operative Relevanz, konkrete Conveyor-/Material-Handling-Anwendungen und belegte Engineering-/Procurement-Schnittstellen; Zugang über Großkonzernstruktur prüfen.",
    "priority": "A",
    "next": "Manuelle Vertriebsprüfung mit Fokus auf mechanische Antriebselemente, Sonderteile und Baugruppen für Förder-/Sortier-/BHS-Module; Einstieg über Procurement Cost Engineering oder Mechanical Engineering am Standort Veghel prüfen.",
    "sources": "https://www.vanderlande.com/ ; https://careers.vanderlande.com/all-jobs/mechanical-project-engineer-i-jr36845/ ; https://careers.vanderlande.com/job-areas/engineering/ ; https://www.vanderlande.com/wp-content/uploads/2025/11/Vanderlande-Industries-B.V.-annual-report-FY25-incl.-auditors-report.pdf",
    "date": "2026-07-31"
  },
  {
    "company": "AWL-Techniek B.V. / AWL Automation",
    "website": "https://awlautomation.com/",
    "region": "Niederlande",
    "location": "Harderwijk, Gelderland",
    "industry": "Robotik, industrielle Automation, Sondermaschinenbau, Intralogistik",
    "description": "Systemintegrator und Maschinenbauer für smarte modulare Maschinen, robotische Automationslösungen, Joining-Technologien, Machine Vision und Material Handling.",
    "need": "Starkes technisches Signal: offizielle Website belegt robotic automation für Produktions- und Intralogistikprozesse, Pick & Place, Parcel Induction, Tote Handling und End-of-arm tooling; A3-Profil belegt Design und Bau smarter modularer Maschinen. Aktuelle Karrierequelle nennt Mechanical Engineer in Harderwijk. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Pick-&-Place-/Handling-Achsen.",
    "relevance": "88/100 - A-Lead: sehr guter Robotik-/Sondermaschinenfit, starke mechanische Baugruppen- und Handlingnähe, Größe belegt; namentliche Ansprechpartner noch offen.",
    "priority": "A",
    "next": "Vor Ansprache Einkaufs-/Engineering-Leitung öffentlich nachrecherchieren; Erstansatz über Sonderteile/Baugruppen für Robotikzellen, End-of-arm tooling und Material-Handling-Module.",
    "sources": "https://awlautomation.com/ ; https://www.automate.org/companies/awl-techniek-b-v ; https://careers.awl.nl/professional/",
    "date": "2026-07-31"
  },
  {
    "company": "BluePrint Automation B.V.",
    "website": "https://www.blueprintautomation.com/",
    "region": "Niederlande",
    "location": "Woerden, Utrecht",
    "industry": "Verpackungstechnik, Verpackungsautomation, Robotik, Maschinenbau",
    "description": "Hersteller von Case-Packern, Tray-Packing- und End-of-Line-Verpackungslösungen für flexible und schwer handhabbare Produkte; nutzt u. a. Pick-and-place und vision-guided robotics.",
    "need": "Starkes technisches Signal: offizielle Website belegt Entwicklung und Fertigung automatisierter Verpackungsmaschinen mit Pick-and-place und vision-guided robotics; Karriereportal 2026 nennt Stellen in Woerden für Industrial Automation, Electrical Design, Mechatronik, Machinebankwerker/Fabricage und Werkvoorbereiding Service; Stellenbeschreibung nennt Upgrades/Modifikationen bestehender Maschinen und Zusammenarbeit mit Mechanical-/Software-/Service-Engineering. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben als Prüfpunkt für Pick-and-place-/Förder-/Positionierachsen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung.",
    "relevance": "90/100 - A-Lead: sehr starker Verpackungsmaschinenfit, robotische Pick-and-place-Anwendungen, aktuelle technische Stellen und offizielle Ansprechpartner-/Managementinformationen.",
    "priority": "A",
    "next": "Vertriebsprüfung mit konkretem Bezug auf Sonderteile/Baugruppen und Antriebskomponenten für Verpackungs-, Pick-and-place- und Service-/Retrofit-Anwendungen; Einstieg über Engineering/Operations oder Material Planning prüfen.",
    "sources": "https://www.blueprintautomation.com/ ; https://www.blueprintautomation.com/bpa-global/team ; https://jobs.blueprintautomation.com/ ; https://jobs.blueprintautomation.com/vacatures/electrical-engineer.html",
    "date": "2026-07-31"
  },
  {
    "company": "Krones AG",
    "website": "https://www.krones.com/",
    "region": "Deutschland / Bayern",
    "location": "Neutraubling",
    "industry": "Verpackungs- und Abfülltechnik, Anlagenbau",
    "description": "Technologieanbieter für Prozess-, Abfüll- und Verpackungstechnik sowie komplette Linien für Getränke- und Lebensmittelhersteller.",
    "need": "Mittleres bis starkes Signal: offizielle Website belegt Prozess-, Füll- und Verpackungsmaschinen; Engineering-/Karrierequellen zeigen Mechanikbezug. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für synchronisierte Verpackungs-/Förderbewegungen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "84/100 - A-Lead: starker Branchenfit, belastbare Größe und konkrete Maschinen-/Linienanwendungen; Konzernbeschaffung ist Zugangshürde.",
    "priority": "A",
    "next": "Lieferanten-/Einkaufszugang prüfen; Einstieg über Spezialteile, Ersatz-/Servicebedarf oder Kleinserien für Packaging/Materialfluss.",
    "sources": "https://www.krones.com/en/index.php ; https://www.krones.com/en/company/investor-relations/krones-group-annual-report-2025.php ; https://www.krones.com/en/career/engineering.php",
    "date": "2026-08-03"
  },
  {
    "company": "Gerhard Schubert GmbH Verpackungsmaschinen",
    "website": "https://www.schubert.group/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Crailsheim",
    "industry": "Verpackungsmaschinen, Robotik, Automatisierung",
    "description": "Hersteller modularer Top-Loading-Verpackungsmaschinen mit eigenen robotischen Technologien und hoher Eigenentwicklung.",
    "need": "Starkes Signal: offizielle Arbeitgeberseite belegt Größe und Robotik-/Verpackungsfokus; RoboJob-Fallstudie belegt eigene Komponentenfertigung und regionales Lieferantennetzwerk. Keine aktuelle Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "88/100 - A-Lead: sehr konkreter Robotik-/Verpackungsfit, Lieferanten- und Komponentenhinweis, Größe offiziell belegt.",
    "priority": "A",
    "next": "Einstieg über Komponentenfertigung/Sonderteile und Lieferantenfähigkeit für mechanische Baugruppen prüfen.",
    "sources": "https://www.schubert.group/en/careers/schubert-as-an-employer/ ; https://robojob.eu/en/2000-installations/customer-testimonials/gerhard-schubert-gmbh/",
    "date": "2026-08-03"
  },
  {
    "company": "MULTIVAC Group",
    "website": "https://multivac.com/",
    "region": "Deutschland / Bayern",
    "location": "Wolfertschwenden",
    "industry": "Verpackungsmaschinen, Lebensmitteltechnik, Linienbau",
    "description": "Hersteller von Maschinen und Linien für Processing, Slicing, Labelling, Inspection und Packaging sensibler Produkte.",
    "need": "Mittleres Signal: offizielle Seite belegt Maschinen und Linien; Stellenquelle für Mechanical Product Design im Tray-/Pouch-Packaging zeigt laufenden mechanischen Entwicklungsbedarf. Keine Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "82/100 - A-Lead: sehr guter Maschinenbau-Fit, belastbare Größenklasse und konkretes Engineering-Signal; exakte aktuelle Gesamtzahl offen.",
    "priority": "A",
    "next": "DACH-Einkaufs-/Engineering-Rolle ermitteln und mit mechanischen Sonder-/Verschleißteilen sowie Baugruppen ansetzen.",
    "sources": "https://multivac.com/int/en/company/multivac-group ; https://multivac.com/bg/en/career/job-vacancies/vacancies.mechanical-product-designer-tray-pouch-packaging-mubg",
    "date": "2026-08-03"
  },
  {
    "company": "Grenzebach Group",
    "website": "https://www.grenzebach.com/",
    "region": "Deutschland / Bayern",
    "location": "Asbach-Bäumenheim / Hamlar",
    "industry": "Industrieautomation, Anlagenbau, Intralogistik",
    "description": "Automationsspezialist für Glas, Baustoffe, Guss, Intralogistik, additive Fertigung sowie Prozess- und Energietechnik.",
    "need": "Mittleres Signal: offizielle Website belegt industrielle Automation und Intralogistik; Engineering-Seite beschreibt Produktdesign, Konstruktion und Entwicklung über mehrere Business Units. Keine Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemen/Lineartechnik anwendungsabhängig",
    "relevance": "83/100 - A-Lead: klare Automation-/Intralogistikanwendungen, belastbare Größe und eigener Engineering-Bezug.",
    "priority": "A",
    "next": "Business Unit Intralogistics oder Special Technologies zuerst qualifizieren und Projekt-/Einkaufsrollen identifizieren.",
    "sources": "https://www.grenzebach.com/en/ ; https://www.grenzebach.com/en/career/career-level-experienced-professionals/direct-entry/functional-area-of-product-design-/-engineering/",
    "date": "2026-08-03"
  },
  {
    "company": "WITRON Logistik + Informatik GmbH",
    "website": "https://www.witron.com/",
    "region": "Deutschland / Bayern",
    "location": "Parkstein",
    "industry": "Intralogistik, Materialflussautomation",
    "description": "Entwickelt und realisiert automatisierte Logistik- und Materialflusssysteme mit Mechanikdesign und Mechanikproduktion.",
    "need": "Mittleres Signal: Unternehmensprofil nennt Logistics Design, Controls, Mechanics Design und Mechanics Production; Karriereportal zeigt laufende technische Rekrutierung. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Förder-/Sortierachsen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "76/100 - B-Lead: sehr guter Intralogistikfit und mechanische Wertschöpfung; exakte Mitarbeiterzahl und Einkaufszugang noch offen.",
    "priority": "B",
    "next": "Offizielle Größen- und Beschaffungsdetails nachziehen; danach Konstruktion oder technischen Einkauf für Projekt-/Ersatzteilbedarf ansprechen.",
    "sources": "https://www.witron.com/ ; https://careers.witron.com/",
    "date": "2026-08-03"
  },
  {
    "company": "Kardex Mlog / Kardex",
    "website": "https://www.kardex.com/",
    "region": "Deutschland / Baden-Württemberg; Schweiz",
    "location": "Neuenstadt am Kocher",
    "industry": "Intralogistik, automatische Lager- und Materialflusssysteme",
    "description": "Kardex bietet automatisierte Lager-, Bereitstell- und Materialflusssysteme; Kardex Mlog entwickelt und fertigt integrierte Material-Handling-Systeme.",
    "need": "Mittleres bis starkes Signal: offizielle Quellen nennen automatisierte Produkte, Material Handling und deutsche Produktion; Karriereseite beschreibt Stacker Cranes, Shuttle Vehicles und Conveyor Systems. Keine Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Shuttle-/Fördersysteme; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "83/100 - A-Lead: belastbare Größe, deutsche Produktionsstandorte und klare Material-Handling-Anwendungen.",
    "priority": "A",
    "next": "Supplier-Quality-/Einkaufsrolle in Neuenstadt bzw. Deutschland prüfen; Bedarf für mechanische Baugruppen und Ersatzteile sondieren.",
    "sources": "https://www.kardex.com/company_people/careers/careers-at-kardex ; https://www.kardex.com/en-us/industry-applications/warehouse/mechanical-engineering",
    "date": "2026-08-03"
  },
  {
    "company": "OPTIMA packaging group GmbH",
    "website": "https://www.optima-packaging.com/de",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Schwäbisch Hall",
    "industry": "Verpackungs- und Abfüllanlagen",
    "description": "Technologiepartner für Abfüll- und Verpackungsanlagen in Pharma, Consumer, Nonwovens und weiteren Segmenten.",
    "need": "Mittleres Signal: offizielles Karriereportal zeigt zahlreiche technische Rollen; Profile nennen Arbeitsvorbereitung, Entwicklung von Werkzeugsystemen, Steuerungstechnik und Automation. Keine Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemenanwendungen in synchronisierten Verpackungsmodulen als Prüfpunkt",
    "relevance": "82/100 - A-Lead: sehr guter Verpackungsmaschinenfit und laufendes technisches Recruiting; Mitarbeiterzahl nur ergänzend belegt.",
    "priority": "A",
    "next": "Technische Einkaufs-/Arbeitsvorbereitungsrollen in Schwäbisch Hall prüfen; Lieferantennutzen für Sonderteile und Baugruppen konkretisieren.",
    "sources": "https://www.optima-packaging.com/de ; https://www.optima-packaging.com/de/karriere ; https://www.optima-packaging.com/de/karriere/aktuelle-stellenangebote",
    "date": "2026-08-03"
  },
  {
    "company": "SSI SCHÄFER Group",
    "website": "https://www.ssi-schaefer.com/",
    "region": "Deutschland / Nordrhein-Westfalen; Österreich",
    "location": "Neunkirchen/Siegerland; Graz u. a.",
    "industry": "Intralogistik, Material Handling, Lagerautomatisierung",
    "description": "Globaler Anbieter modularer Lager- und Logistiksysteme für Lagerung, Kommissionierung und Transportprozesse.",
    "need": "Mittleres bis starkes technisches Signal: offizielle Website belegt modulare Intralogistiksysteme; technisches Unternehmensprofil zu SSI Schäfer PEEM beschreibt Entwicklung und Fertigung dynamischer Förderanlagen für Behälter und Kartons. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben und Förderantriebe; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "87/100 - A-Lead: sehr starker Intralogistik- und Fördertechnikfit; Größe groß, aber heutige Direktprüfung technisch nicht möglich.",
    "priority": "A",
    "next": "DACH-Einkaufsorganisation für Fördertechnik/Mechanik segmentieren und Lieferantenportal bzw. Materialgruppen prüfen.",
    "sources": "https://www.ssi-schaefer.com/ ; https://www.warehouse-logistics.com/download/Flyer/GB_Flyer_Firma_Salomon_002.pdf ; https://www.linkedin.com/company/ssischaefer",
    "date": "2026-08-03"
  },
  {
    "company": "BEUMER Group GmbH & Co. KG",
    "website": "https://www.beumergroup.com/",
    "region": "Deutschland / Nordrhein-Westfalen",
    "location": "Beckum",
    "industry": "Fördertechnik, Intralogistik, Verpackung, Sortation",
    "description": "Internationaler Anbieter von Intralogistiklösungen für Fördern, Beladen, Palettieren, Verpacken, Sortieren und Gepäckabfertigung.",
    "need": "Starkes technisches Signal: offizielle Website belegt Förder-, Palettier-, Verpackungs- und Sortierlösungen sowie Lifecycle-Service. Dies spricht für mechanische Komponenten- und Ersatzteilbedarfe, ohne konkrete Beschaffungsabsicht zu belegen.",
    "fit": "Antriebstechnik; Zahnriemen/Antriebselemente für Förder-/Sortierbewegungen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "86/100 - A-Lead: sehr starker Fördertechnikfit, belastbare Größenklasse und breite mechanische Anwendungen; etablierte Rahmenlieferanten wahrscheinlich.",
    "priority": "A",
    "next": "Beschaffungsweg und Materialgruppen für mechanische Antriebselemente prüfen; Einstieg über Service-/Ersatzteil- oder Projektgeschäft vorbereiten.",
    "sources": "https://www.beumergroup.com/ ; https://www.beumergroup.com/career/",
    "date": "2026-08-03"
  },
  {
    "company": "HAHN Automation Group",
    "website": "https://www.hahnautomation.group/",
    "region": "Deutschland / Rheinland-Pfalz",
    "location": "Rheinböllen",
    "industry": "Sondermaschinenbau, Factory Automation, Robotik",
    "description": "Entwickelt, konstruiert, baut und integriert kundenspezifische Automations- und Robotiklösungen, Produktionslinien sowie Prüf- und Fertigungssysteme.",
    "need": "Mittleres technisches Signal: offizielle Website belegt kundenspezifische Konstruktion und Integration physischer Automations-/Robotiksysteme; Karriereportal zeigte aktive technische Rekrutierung. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung; Zahnriemen/Lineartechnik für Handhabungsachsen",
    "relevance": "78/100 - B-Lead: sehr starker Branchen- und Sondermaschinenfit; exakte aktuelle Mitarbeiterzahl und Beschaffungsstruktur offen.",
    "priority": "B",
    "next": "Standorte Rheinböllen und Diepenau nach Konstruktion und technischem Einkauf segmentieren; Größenbeleg vor Erstansprache nachziehen.",
    "sources": "https://www.hahnautomation.group/ ; https://careers.hahnautomation.group/ ; https://careers.hahnautomation.group/jobboard/",
    "date": "2026-08-03"
  },
  {
    "company": "Swisslog AG",
    "website": "https://www.swisslog.com/",
    "region": "Schweiz / Aargau; DACH",
    "location": "Buchs AG; Dortmund u. a.",
    "industry": "Intralogistik, Warehouse Automation",
    "description": "Anbieter automatisierter Lager- und Materialflusssysteme; Teil des KUKA-Konzerns.",
    "need": "Mittleres bis starkes technisches Signal: eine direkt geprüfte Mechanical-Engineer-Stelle verlangte CAD sowie mechanische Installation für Automated Material Handling; weitere Projektquelle nannte Förderer, Krane und Monorail. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Lineartechnik; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "76/100 - B-Lead: konkrete Material-Handling-Anwendungen und Engineering-Signal; exakte Größe und Einkaufszugang offen.",
    "priority": "B",
    "next": "DACH-Organisation und Einkaufszugang klären; mechanische Subsysteme für Conveyor-, Stacker-Crane- und Monorail-Anwendungen fokussieren.",
    "sources": "https://www.swisslog.com/ ; https://www.swisslog.com/en-us/careers/openings/mechanical-engineer-4142 ; https://jobs.smartrecruiters.com/SwisslogUKLtd/743999703113380-maintenance-manager-automated-warehouse",
    "date": "2026-08-03"
  },
  {
    "company": "Mosca GmbH",
    "website": "https://www.mosca.com/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Waldbrunn",
    "industry": "Verpackungstechnik, End-of-Line-Automation",
    "description": "Entwickelt Umreifungsmaschinen, Umreifungsmaterial und komplexe Systeme zur Transportsicherung.",
    "need": "Mittleres technisches Signal: offizielle Website belegt Umreifungsmaschinen und komplexe Systeme; ergänzende Konzernquelle zeigte Electro-Mechanical- und Engineering-Rollen für End-of-Line-Lösungen. Keine konkrete Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "73/100 - B-Lead: guter Verpackungsmaschinenfit; Größenbeleg und DACH-spezifisches aktuelles Signal noch nachzuschärfen.",
    "priority": "B",
    "next": "Deutschen Einkauf/Engineering-Zugang und Größenbeleg verifizieren; mit Sonderteilen oder Baugruppen für Umreifungs-/Fördermodule ansetzen.",
    "sources": "https://www.mosca.com/ ; https://www.mosca.com/en/career ; https://www.eammosca.com/ ; https://www.eammosca.com/career",
    "date": "2026-08-03"
  },
  {
    "company": "Cama Group",
    "website": "https://camagroup.com/",
    "region": "Italien / Lombardei",
    "location": "Molteno (Lecco)",
    "industry": "Verpackungsmaschinen, Robotik, End-of-Line-Automation",
    "description": "Entwickelt und baut sekundäre/tertiäre Verpackungsmaschinen, komplette Linien und eigene Delta-Robotik für Food, Pharma sowie Personal/Home Care.",
    "need": "Starkes aktuelles technisches Signal: Interpack-2026-Portfolio mit drei real vorgeführten hochrobotisierten Maschinen, modularen Monobloc-Systemen, Servo- und eigener Robotiktechnologie.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "90/100 - A-Lead: sehr konkreter Verpackungs-/Robotikfit, aktuelle Produktneuheiten und offizielle Größe; Beschaffungsabsicht nicht belegt.",
    "priority": "A",
    "next": "Technischen Einkauf bzw. Mechanical Engineering identifizieren und mit Sonderteilen/Baugruppen für Servo-, Robotik- und Verpackungsmodule ansprechen.",
    "sources": "https://camagroup.com/ ; https://camagroup.com/cama-group-at-interpack-2026/ ; https://camagroup.com/packaging-lines/",
    "date": "2026-08-04"
  },
  {
    "company": "Marchesini Group S.p.A.",
    "website": "https://www.marchesini.com/",
    "region": "Italien / Emilia-Romagna",
    "location": "Pianoro / Bologna",
    "industry": "Pharma- und Kosmetik-Verpackungsmaschinen",
    "description": "Entwickelt und produziert automatische Maschinen und komplette Linien für Pharma- und Kosmetikverarbeitung sowie Verpackung.",
    "need": "Starkes Signal: aktuelle Maschinen-/Linienangebote, eigene Produktion und Montage; offizielle Stellenbeschreibung 2026 nennt mechanische Montage, technische Zeichnungen sowie FAT/SAT automatischer Verpackungsmaschinen.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "91/100 - A-Lead: sehr starker Pharma-Verpackungsfit, belastbare Größe und konkrete mechanische Fertigungs-/Montagesignale.",
    "priority": "A",
    "next": "Lieferanten- und Einkaufszugang in Pianoro prüfen; Einstieg über formatabhängige Sonderteile, Baugruppen und mechanische Ersatzteile vorbereiten.",
    "sources": "https://www.marchesini.com/en/corporate/the-group ; https://www.marchesini.com/en/corporate/work-with-us/mechanical-fitter ; https://www.marchesini.com/sites/default/files/2025-12/Sustainability%20Report%202024.pdf",
    "date": "2026-08-04"
  },
  {
    "company": "IMA Group",
    "website": "https://imagroup.com/",
    "region": "Italien / Emilia-Romagna",
    "location": "Ozzano dell'Emilia / Bologna",
    "industry": "Verpackungsmaschinen, Pharma-, Food- und Industrieautomation",
    "description": "Weltweit tätiger Hersteller automatischer Maschinen für Pharma, Medizintechnik, Food und Konsumgüter sowie industrielle Prozessautomation.",
    "need": "Starkes aktuelles Signal: offizieller Investorbereich 2026 bestätigt Entwicklung und Produktion automatischer Maschinen sowie 56 Manufacturing Sites; 2025-Nachhaltigkeitsbericht ist veröffentlicht.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "87/100 - A-Lead: sehr großer, passender Maschinenbauer mit breiter Produktion; exakte aktuelle Mitarbeiterzahl und Einkaufssegmentierung offen.",
    "priority": "A",
    "next": "Zunächst passende italienische Business Unit und Materialgruppe identifizieren; Spezial-/Formatteile oder Baugruppen statt generischer Konzernansprache fokussieren.",
    "sources": "https://imagroup.com/corporate/investors/ ; https://imagroup.com/",
    "date": "2026-08-04"
  },
  {
    "company": "Cimcorp Group",
    "website": "https://cimcorp.com/",
    "region": "Finnland",
    "location": "Ulvila",
    "industry": "Intralogistik, Robotik, Materialflussautomation",
    "description": "Automationsintegrator für robotische Materialflusssysteme in Lebensmittelhandel, Reifen-, EV-Batterie- und Postlogistik.",
    "need": "Starkes Signal: Nachhaltigkeitsbericht 2025 belegt 516 Mitarbeitende sowie Design, Fertigung, Installation und Support von Automation einschließlich Upgrades und Ersatzteilen.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "92/100 - A-Lead: klar belegte Fertigung robotischer Intralogistiksysteme, aktuelle Größe und expliziter Ersatzteil-/Upgrade-Bezug.",
    "priority": "A",
    "next": "Procurement oder Mechanical Engineering in Ulvila ansprechen; mechanische Baugruppen, Sonderteile und Lifecycle-Ersatzteile als Einstieg priorisieren.",
    "sources": "https://cimcorp.com/ ; https://cimcorp.com/app/uploads/2026/04/Cimcorp-Group-Sustainability-report.pdf ; https://cimcorp.com/career-opportunities/open-application/",
    "date": "2026-08-04"
  },
  {
    "company": "Coesia S.p.A.",
    "website": "https://www.coesia.com/",
    "region": "Italien / Emilia-Romagna",
    "location": "Bologna",
    "industry": "Verpackungsmaschinen, Industrieautomation, Intralogistik",
    "description": "Industriegruppe mit 21 Unternehmen für automatische Verpackungsmaschinen, Prozesslösungen, Factory Automation und Intralogistik.",
    "need": "Starkes Signal: offizielle 2025/2026-Seiten zeigen neue Verpackungsmaschinen, robotische Food-Handhabung, AI-Palettierung und ein breites Produktionsnetz.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "78/100 - B-Lead: großer, technisch sehr passender Maschinenverbund; eigene Transmission-/Gear-Aktivitäten schaffen möglichen Wettbewerbs- oder Eigenfertigungskonflikt.",
    "priority": "B",
    "next": "Vor Ansprache eine konkrete Coesia-Marke ohne direkten Komponentenwettbewerb auswählen und deren lokalen Einkauf prüfen.",
    "sources": "https://www.coesia.com/en/group/coesia ; https://www.coesia.com/en/exhibitions/coesia-at-pack-expo-las-vegas-2025-dive-into-the-automation-evolution ; https://www.coesia.com/en",
    "date": "2026-08-04"
  },
  {
    "company": "Sidel",
    "website": "https://www.sidel.com/",
    "region": "Frankreich / Italien / Europa",
    "location": "Octeville-sur-Mer; Parma u. a.",
    "industry": "Abfüll- und Verpackungslinien, Robotik, End-of-Line",
    "description": "Entwickelt und fertigt Maschinen und komplette Hochgeschwindigkeitslinien für Getränke, Food sowie Home/Personal Care.",
    "need": "Starkes aktuelles Signal: Interpack 2026 mit neuer RoboSELEX-Roboterkollation und RoboAccess-Palettierung; 2025-Zertifikat belegt Design und Fertigung von Maschinen und robotischen Transportlinien.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "86/100 - A-Lead: hochkonkreter Linien-, Robotik- und Mechanikfit; exakte aktuelle Mitarbeiterzahl nicht direkt ausgewiesen.",
    "priority": "A",
    "next": "Europäischen Einkaufsstandort bzw. Parma-Mechanikfertigung qualifizieren und mit Sonderteilen/Baugruppen für Robotik- und End-of-Line-Module ansetzen.",
    "sources": "https://www.sidel.com/en/about/media/press-releases/sidel-at-interpack-2026/ ; https://www.sidel.com/media/r3qb4wsw/0029395-ems-engus-ukas_14001.pdf ; https://www.sidel.com/",
    "date": "2026-08-04"
  },
  {
    "company": "SACMI Group / Packaging & Chocolate",
    "website": "https://sacmi.com/",
    "region": "Italien / Emilia-Romagna",
    "location": "Imola; Alba; Bologna; Mailand",
    "industry": "Verpackungsmaschinen, Lebensmitteltechnik, Industrieanlagen",
    "description": "Maschinenbaugruppe mit eigener Business Unit für Primär-/Sekundärverpackung und Schokoladenverarbeitung.",
    "need": "Starkes Signal: 2025 vorgestellte Verpackungsmaschinen mit bis zu 40 unabhängigen Antrieben, modularer Serienarchitektur sowie Pick-and-place-Robotik; mehrere europäische Produktionsstätten belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "89/100 - A-Lead: belastbare Größe, eigene Werke und sehr konkreter Verpackungs-/Antriebsbezug.",
    "priority": "A",
    "next": "Einkauf der Packaging-&-Chocolate-Werke Alba/Bologna segmentieren; Sonderteile und Baugruppen für antriebsreiche Verpackungsmodule anbieten.",
    "sources": "https://sacmi.com/de-de/packaging/news/21733/sacmi-packaging-chocolate-at-fachpack-2025 ; https://sacmi.com/en-US/ipack-ima-2025 ; https://sacmi.com/en-US/las-vegas-2025",
    "date": "2026-08-04"
  },
  {
    "company": "pester pac automation GmbH",
    "website": "https://www.pester.com/",
    "region": "Deutschland / Bayern",
    "location": "Wolfertschwenden",
    "industry": "Pharma- und Consumer-Verpackung, End-of-Line-Automation",
    "description": "Entwickelt Folienverpackungs-, Kartonier-, Casepacking- und Palettiermaschinen sowie kundenspezifische Turnkey-Linien.",
    "need": "Starkes aktuelles Signal: Interpack 2026 mit neuer Maschinenarchitektur; offizielle Historie nennt Ausbau und Modernisierung der eigenen Komponentenfertigung, ISO-Zertifikat Entwicklung, Produktion und Montage von Verpackungsmaschinen.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "88/100 - A-Lead: sehr guter End-of-Line-Fit, offizielle Größe und konkreter Komponentenfertigungsbezug.",
    "priority": "A",
    "next": "Einkauf bzw. Komponentenfertigung in Wolfertschwenden prüfen; Spitzenlast-, Spezialteil- oder vormontierte Baugruppen als Nutzenhypothese testen.",
    "sources": "https://www.pester.com/ ; https://www.pester.com/en/company/pester-pac-automation/profile/ ; https://www.pester.com/med/pester-iso9001-en.pdf",
    "date": "2026-08-04"
  },
  {
    "company": "Harro Höfliger Verpackungsmaschinen GmbH",
    "website": "https://hoefliger.com/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Allmersbach im Tal; Backnang; Aspach; Satteldorf",
    "industry": "Pharma-/Medizintechnik-Produktions- und Verpackungsanlagen",
    "description": "Entwickelt kundenspezifische Prozess-, Montage- und Verpackungssysteme vom Labor bis zur Turnkey-Linie.",
    "need": "Starkes Signal: 2025/2026 belegter Ausbau des Verpackungsportfolios; Satteldorf begleitet Großprojekte von Konstruktion und Vormontage bis Linienintegration; strategische Partner werden ausdrücklich genannt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "93/100 - A-Lead: sehr starker kundenspezifischer Maschinenbau- und Baugruppenfit, belastbare Größe und explizite Partnerorientierung.",
    "priority": "A",
    "next": "Satteldorf und zentrale Einkaufsorganisation getrennt prüfen; Einstieg über Großprojekte, Vormontage und kundenspezifische mechanische Baugruppen.",
    "sources": "https://hoefliger.com/en/about-us ; https://hoefliger.com/en/about-us/news/20-years-of-the-satteldorf-site ; https://hoefliger.com/en/products/consumer/packaging",
    "date": "2026-08-04"
  },
  {
    "company": "Romaco Group",
    "website": "https://www.romaco.com/",
    "region": "Deutschland / Italien / Spanien",
    "location": "Karlsruhe, Köln, Steinen; Bologna; Barcelona",
    "industry": "Pharma-Verarbeitungs- und Verpackungsmaschinen",
    "description": "Hersteller von Verarbeitungs- und Verpackungstechnik für pharmazeutische Pulver, Granulate, Tabletten und Kapseln mit sieben Produktmarken.",
    "need": "Starkes aktuelles Signal: 2025 Lokalisierung der Formatteilproduktion und Ausbau mehrerer Produktions-/Experience-Standorte; neue Blistermaschinen mit Servo-Technik und Schnittstellen zu Kartonierer/Casepacker.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "88/100 - A-Lead: belastbare Größe, mehrere europäische Werke und aktueller Formatteil-/Servo-Bezug.",
    "priority": "A",
    "next": "Karlsruher Einkauf und Formatteilorganisation qualifizieren; Sonder-/Formatteile sowie mechanische Baugruppen für Blister- und End-of-Line-Systeme fokussieren.",
    "sources": "https://www.romaco.com/career/who-we-are ; https://www.romaco.com/press-news/details/romaco-at-cphi-pmec-india-2025 ; https://www.romaco.com/press-news/details/romaco-at-pack-expo-in-las-vegas-usa",
    "date": "2026-08-04"
  },
  {
    "company": "Hugo Beck Maschinenbau GmbH & Co. KG",
    "website": "https://www.hugobeck.com/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Dettingen/Erms",
    "industry": "Verpackungsmaschinen, Automatisierung, Maschinenbau",
    "description": "Entwickelt und fertigt kundenspezifische horizontale Folien- und Papierverpackungsmaschinen, Flowpack-/Form-Fill-and-Seal-Systeme sowie Robotik- und Handhabungslösungen.",
    "need": "Starkes aktuelles technisches Signal: neue paper-S-Bündelpackmaschine zur interpack 2026; offizielle Produktseite belegt kundenspezifische In-house-Projektierung und Fertigung sowie moderne Antriebs-/Steuerungstechnik. Keine Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für synchronisierte Verpackungs-/Zuführachsen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "90/100 - A-Lead: offizielle Größe, eigene Fertigung, konkreter Servo-/Automationsbezug und aktuelle Maschinenneuheit.",
    "priority": "A",
    "next": "Technischen Einkauf und Konstruktion in Dettingen qualifizieren; mit Sonderteilen, vormontierten Baugruppen und Antriebselementen für Zuführ-/Verpackungsachsen ansetzen.",
    "sources": "https://www.hugobeck.com/en/ ; https://www.hugobeck.com/en/solutions-portfolio/ ; https://www.hugobeck.com/en/company/newsroom/press-releases/hugo-beck-to-launch-new-sleeve-wrapper-for-sustainable-transport-packaging-at-interpack",
    "date": "2026-08-05"
  },
  {
    "company": "SN Maschinenbau GmbH",
    "website": "https://www.sn-packaging.com/",
    "region": "Deutschland / Nordrhein-Westfalen",
    "location": "Wipperfürth",
    "industry": "Verpackungsmaschinen, Lebensmittel-/Pharma-/Kosmetiktechnik",
    "description": "Entwickelt und baut kundenspezifische horizontale Form-, Füll- und Verschließmaschinen sowie Beutelverpackungslösungen.",
    "need": "Starkes aktuelles Signal: 2026 neue HSF 100 und FLH 300; offizielle Seite belegt Entwicklung, Konstruktion und Fertigung am Standort sowie hohe Fertigungstiefe. Konkrete Beschaffungsabsicht nicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für getaktete/rotierende Verpackungsachsen; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "91/100 - A-Lead: belastbare Größe, kundenspezifischer Maschinenbau, aktuelle Produktneuheiten und vollständige Entwicklung/Fertigung am Standort.",
    "priority": "A",
    "next": "Einkauf/Konstruktion in Wipperfürth prüfen; Nutzenhypothese für Spitzenlast-Sonderteile, Formatkomponenten und vormontierte mechanische Baugruppen testen.",
    "sources": "https://www.sn-packaging.com/en/company/sn/about-us ; https://www.sn-packaging.com/ ; https://www.packaging-labelling.com/pressreleases/packaging-know-how-and-film-expertise",
    "date": "2026-08-05"
  },
  {
    "company": "Uhlmann Pac-Systeme GmbH & Co. KG",
    "website": "https://www.uhlmann.de/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Laupheim",
    "industry": "Pharma-Verpackungsmaschinen, Automatisierung",
    "description": "Turnkey-Anbieter für integrierte pharmazeutische Verpackungslösungen aus Maschinen, Software und Services; Blister-, Flaschen-, Kartonier- und Linienlösungen.",
    "need": "Starkes aktuelles Signal: interpack 2026 mit neuen OEE-orientierten Lösungen und nachhaltigen Tray-Konzepten; offizieller Service nennt Ersatzteile, Formatteile, Upgrades und Modernisierung. Keine konkrete externe Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben; CNC-Lohnfertigung/Sonder-/Formatteile; Baugruppenfertigung",
    "relevance": "92/100 - A-Lead: sehr starker Pharma-Verpackungsfit, belastbare Größe und konkreter Formatteil-/Ersatzteil-/Upgrade-Bezug.",
    "priority": "A",
    "next": "Einkauf und Formatteilorganisation in Laupheim qualifizieren; Sonder-/Formatteile und Baugruppen für Modernisierung und Lifecycle-Geschäft fokussieren.",
    "sources": "https://interpack.event.uhlmann.de/en/ ; https://sustainability.uhlmann.de/uhlmann-pac/es/career/apprenticeships-and-dual-study-courses ; https://www.uhlmann.de/en/products-and-solutions/customer-service-at-a-glance",
    "date": "2026-08-05"
  },
  {
    "company": "Bausch+Ströbel SE + Co. KG",
    "website": "https://www.bausch-stroebel.com/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Ilshofen",
    "industry": "Pharma-Maschinenbau, Abfüll- und Verpackungsanlagen",
    "description": "Entwickelt und baut kundenspezifische Maschinen und vollautomatische Linien für Reinigung, Sterilisation, Abfüllung, Verschluss, Inspektion, Montage, Förderung und Etikettierung pharmazeutischer Behälter.",
    "need": "Starkes aktuelles Signal: interpack 2026 zeigt neue Anlagen-/Komponentenkonzepte; 2026 ausgezeichnete additive Fertigung für funktionsoptimierte pharmazeutische Komponenten und interne Weiterentwicklung seit 2020. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Förder-/Handlingachsen als Prüfpunkt; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "89/100 - A-Lead: sehr großer kundenspezifischer Pharma-Maschinenbauer mit aktueller Komponenteninnovation und hoher vertikaler Integration.",
    "priority": "A",
    "next": "Einkauf/Engineering in Ilshofen qualifizieren; zunächst konventionell gefertigte Sonderteile und vormontierte Baugruppen außerhalb additiv optimierter Kernteile adressieren.",
    "sources": "https://www.bausch-stroebel.com/en/company/company/history/ ; https://www.bausch-stroebel.com/en/company/current/news-complete/additive-manufacturing ; https://www.bausch-stroebel.com/en/company/current/press",
    "date": "2026-08-05"
  },
  {
    "company": "BHS Corrugated Maschinen- und Anlagenbau GmbH",
    "website": "https://www.bhs-world.com/",
    "region": "Deutschland / Bayern",
    "location": "Weiherhammer",
    "industry": "Wellpappenmaschinen, Automatisierung, Intralogistik, Anlagenbau",
    "description": "Entwickelt und baut komplette Wellpappenanlagen, Digitaldruck-, Automatisierungs- und Intralogistiklösungen sowie Lifecycle- und Ersatzteilsysteme.",
    "need": "Starkes aktuelles Signal: 2026 Einführung des neuen Slitter Scorer SR-C und NextGraphX; 2025 Einführung des intelligenten iBelt-Ersatzteilsystems. Das belegt laufende Komponenten- und Maschineninnovation, jedoch keine externe Beschaffungsabsicht.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für synchronisierte Anlagenachsen als Prüfpunkt; CNC-Lohnfertigung/Sonderteile; Baugruppenfertigung",
    "relevance": "91/100 - A-Lead: belastbare Größe, komplexer Anlagenbau, Intralogistik und mehrere aktuelle mechaniknahe Produktneuheiten.",
    "priority": "A",
    "next": "Technischen Einkauf in Weiherhammer qualifizieren; mit Sonderteilen, vormontierten mechanischen Baugruppen und Antriebselementen für Corrugator-/Upgrade-Projekte ansetzen.",
    "sources": "https://www.bhs-world.com/en/news/product-news ; https://www.bhs-world.com/karriere/bhs-corrugated-360-grad/zahlen-storys ; https://www.bhs-world.com/en/corruverse",
    "date": "2026-08-05"
  },
  {
    "company": "FOCKE & CO. (GmbH & Co. KG) / FOCKE Gruppe",
    "website": "https://www.focke.com/",
    "region": "Deutschland / Niedersachsen",
    "location": "Verden (Aller); Barßel; Berlin",
    "industry": "Verpackungsmaschinen, Automatisierung, End-of-Line",
    "description": "Entwickelt und fertigt Hochgeschwindigkeits-Verpackungsmaschinen und modulare Linien für Tobacco/Nicotine, Hygiene, Tissue, Food und Consumer einschließlich Case Packing und Palettierung.",
    "need": "Starkes technisches Signal: aktuelle Smart Line und Hi5/Agility-Plattform mit modularen Konzepten und ausdrücklich fortschrittlicher Antriebs- bzw. Servo-Technik; Messe- und Produktaktivität 2026. Keine konkrete externe Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für hochdynamische synchronisierte Achsen; CNC-Lohnfertigung/Sonder-/Formatteile; Baugruppenfertigung",
    "relevance": "89/100 - A-Lead: sehr großer Verpackungsmaschinenbauer mit Hochgeschwindigkeitsachsen, modularen Neuentwicklungen und klarer Antriebstechniknähe.",
    "priority": "A",
    "next": "Einkaufs- und Konstruktionszuständigkeit in Verden bzw. Barßel trennen; Nutzenhypothese für Antriebselemente, Format-/Sonderteile und Baugruppen an konkreter Maschinenplattform testen.",
    "sources": "https://www.focke.com/ ; https://www.focke.com/cigarette-packaging-otp/ ; https://www.focke.com/cigarette-packaging-otp-v2/smart-line/ ; https://www.focke.com/hygiene-tissue-food-consumer/",
    "date": "2026-08-05"
  },
  {
    "company": "GEA Group Aktiengesellschaft / Food Processing & Packaging",
    "website": "https://www.gea.com/",
    "region": "Deutschland / Nordrhein-Westfalen; international",
    "location": "Düsseldorf; relevante europäische Food-Processing- und Packaging-Standorte",
    "industry": "Lebensmittel- und Pharma-Maschinenbau, Verpackungstechnik, Prozessanlagen",
    "description": "Internationaler Technologieanbieter für Maschinen, Anlagen, Komponenten und Services in Lebensmittel, Getränke und Pharma; integrierte Verarbeitungs- und Verpackungslinien.",
    "need": "Starkes aktuelles Signal: Markteinführung des PowerPak 5000 zur interpack 2026, integriert mit OptiSlicer, OptiLoader und PowerLabel zu einer synchronisierten Linie bis 600 kg/h; mehrere weitere Maschinenneuheiten 2026. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für synchronisierte Verpackungs-/Zuführachsen; CNC-Lohnfertigung/Sonder-/Formatteile; Baugruppenfertigung",
    "relevance": "90/100 - A-Lead: sehr große operative Relevanz, neue synchronisierte Verpackungslinie und breiter Komponenten-/Baugruppenfit.",
    "priority": "A",
    "next": "Relevante deutsche/europäische Packaging-Einkaufseinheit und konkreten PowerPak-Fertigungsstandort ermitteln; erst danach gezielt mit Antriebselementen und Sonder-/Formatteilen ansprechen.",
    "sources": "https://www.gea.com/ja/news/trade-press/2026/powerpak-5000-thermoformer-launch/ ; https://www.gea.com/pt/events/interpack-2026/ ; https://www.gea.com/en/products/filling-packaging/",
    "date": "2026-08-05"
  },
  {
    "company": "groninger group / groninger & co. gmbh",
    "website": "https://www.groninger-group.com/",
    "region": "Deutschland / Baden-Württemberg",
    "location": "Crailsheim; Schnelldorf",
    "industry": "Pharma-, Kosmetik- und Consumer-Healthcare-Maschinenbau",
    "description": "Entwickelt und fertigt kundenspezifische Füll- und Verschließmaschinen sowie komplette Linien für Pharma, Consumer Healthcare und Kosmetik.",
    "need": "Sehr starkes aktuelles Signal: neue Montagehalle und Bürokomplex; beim Richtfest 2026 wurde der Ausbau mit zu klein gewordenen Bestandsflächen begründet. Zusätzlich nennt der Service Neubau von Formatteilen sowie Austausch spezifischer Komponenten. Keine externe Beschaffungsabsicht belegt.",
    "fit": "Antriebstechnik; Zahnriemen/Zahnriemenscheiben für Förder-/Handlingachsen als Prüfpunkt; CNC-Lohnfertigung/Sonder-/Formatteile; Baugruppenfertigung",
    "relevance": "93/100 - A-Lead: belastbare Größe, kundenspezifischer Pharma-Maschinenbau, laufender Montageausbau und konkreter Formatteil-/Komponentenbezug.",
    "priority": "A",
    "next": "Einkauf und Montage-/Formatteilorganisation in Crailsheim qualifizieren; Kapazitätsausbau als Anlass für Sonderteile und vormontierte mechanische Baugruppen nutzen.",
    "sources": "https://www.groninger-group.com/en/company/about-groninger/ ; https://www.groninger-group.com/en/news-downloads/press-releases/ ; https://www.groninger-group.com/en/services/service-portfolio/",
    "date": "2026-08-05"
  }
];
