window.LEADS = [
  {
    "company": "WITRON Logistik + Informatik GmbH",
    "website": "https://witron.de/",
    "region": "Deutschland",
    "location": "Parkstein, Deutschland",
    "industry": "Intralogistik / Fördertechnik",
    "description": "7.500 Beschäftigte weltweit, davon 2.500 in Parkstein (2026)",
    "need": "2025: Rekordauftragseingang über 2 Mrd. EUR; neue automatisierte Lebensmittel-Logistikprojekte und mechanische Komponentenentwicklung.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "98/100",
    "priority": "A",
    "next": "Beschaffung zu Kapazitätsspitzen und Make-or-buy für mechanische Module qualifizieren.",
    "sources": "https://witron.de/en/news/record-order-intake-in-the-companys-history | https://witron.de/en/",
    "date": "2026-08-12"
  },
  {
    "company": "STADLER Anlagenbau GmbH",
    "website": "https://w-stadler.de/",
    "region": "Deutschland",
    "location": "Altshausen, Deutschland",
    "industry": "Anlagenbau / Sortier- und Fördertechnik",
    "description": "knapp 650 Beschäftigte",
    "need": "2026: neuer Air Drum Sifter und neue hochautomatisierte Sortieranlagen; über 600 realisierte Anlagen.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Bedarf für Antriebs- und Positionierkomponenten in neuen Sortiermodulen prüfen.",
    "sources": "https://w-stadler.de/en/ | https://w-stadler.de/en/company",
    "date": "2026-08-12"
  },
  {
    "company": "Dürr Group / Dürr Systems AG",
    "website": "https://www.durr-group.com/",
    "region": "Deutschland",
    "location": "Bietigheim-Bissingen, Deutschland",
    "industry": "Maschinen- und Anlagenbau / Automation",
    "description": "17.881 Beschäftigte (31.12.2025)",
    "need": "2025/26: Sustainable.Automation als Kernstrategie; Q4-Auftragseingang +19,9 % und Effizienzprogramm bei BBS Automation.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "92/100",
    "priority": "A",
    "next": "Materialgruppen für mechanische Sonderteile und Automationsbaugruppen der deutschen Standorte identifizieren.",
    "sources": "https://www.durr-group.com/en/company/overview | https://www.durr-group.com/en/media/news/news-detail/view/duerr-group-significantly-improves-profitability-114080",
    "date": "2026-08-12"
  },
  {
    "company": "Mikron Group",
    "website": "https://www.mikron.com/",
    "region": "Schweiz",
    "location": "Boudry, Schweiz",
    "industry": "Automation / Präzisionsmaschinenbau",
    "description": "1.570 Beschäftigte (Ende 2025)",
    "need": "2025: Automation-Umsatz auf CHF 250,1 Mio. gestiegen; solider Auftragsbestand und starke Nachfrage aus Pharma/Diagnostik in Europa.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "95/100",
    "priority": "A",
    "next": "Schweizer Automation-Standorte zu Präzisionsteilen und vormontierten mechanischen Einheiten qualifizieren.",
    "sources": "https://2025.report.mikron.com/wp-content/uploads/2026/02/Mikron_Annual_Report_2025.pdf | https://2025.report.mikron.com/key-figures/spreadsheet/",
    "date": "2026-08-12"
  },
  {
    "company": "teamtechnik Industrieausrüstung GmbH",
    "website": "https://teamtechnik.de/",
    "region": "Deutschland",
    "location": "Freiberg am Neckar, Deutschland",
    "industry": "Montage- und Prüftechnik / Automation",
    "description": "Gruppenbeleg: über 300 Beschäftigte allein bei der polnischen Automationseinheit",
    "need": "2025: organisatorische Bündelung und Fortführung kundenspezifischer automatisierter Montage- und Prüflinien; Komponentenfertigung an mehreren Standorten.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "86/100",
    "priority": "A",
    "next": "Aktuelle Beschaffungsorganisation und Fremdvergabe für Montage-/Prüfanlagen verifizieren.",
    "sources": "https://teamtechnik.de/ueber-uns/ | https://teamtechnik.pl/en/about-us/ | https://teamtechnik.pl/en/next-starts-now-2/",
    "date": "2026-08-12"
  },
  {
    "company": "KNOLL Maschinenbau GmbH",
    "website": "https://www.knoll-mb.de/",
    "region": "Deutschland",
    "location": "Bad Saulgau, Deutschland",
    "industry": "Fördertechnik / Maschinenbau / Automation",
    "description": "rund 1.200 Beschäftigte weltweit (2025)",
    "need": "2025/26: neue automatisierte Späneentsorgung, Click.it-Automation, Ausbau der US-Montage und Übernahme von Mercatus.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Bad Saulgau zu Sonderteilen, Antriebskomponenten und Kapazitätsspitzen qualifizieren.",
    "sources": "https://www.knoll-mb.de/en/ | https://www.knoll-mb.de/en/news/company/55-years-knoll | https://www.knoll-mb.de/en/news/press-release/stronger-presence-in-the-usa",
    "date": "2026-08-12"
  },
  {
    "company": "Bystronic AG",
    "website": "https://www.bystronic.com/",
    "region": "Schweiz",
    "location": "Niederönz, Schweiz",
    "industry": "Maschinenbau / Blechbearbeitung / Automation",
    "description": "über 2.900 Beschäftigte weltweit (2025)",
    "need": "2025: Smart-Factory-Konzept sowie neue Biege- und Laserautomation; Konsolidierung der Automationsproduktion.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "91/100",
    "priority": "A",
    "next": "Niederönz-Einkauf zu mechanischen Sonderteilen und modularen Automationsbaugruppen prüfen.",
    "sources": "https://report.bystronic.com/2025/bystronic | https://report.bystronic.com/2025/app/uploads/Annual-Report-2025.pdf",
    "date": "2026-08-12"
  },
  {
    "company": "Komax Group",
    "website": "https://www.komaxgroup.com/",
    "region": "Schweiz",
    "location": "Dierikon, Schweiz",
    "industry": "Automatisierter Maschinenbau / Kabelverarbeitung",
    "description": "3.167 Beschäftigte (31.12.2025)",
    "need": "2025: CHF 70,9 Mio. F&E, mehrere neue Maschinen und Inline-Prüfsysteme; 633 Mitarbeitende in F&E/Engineering.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Schweizer Beschaffung für kundenspezifische Anwendungen, Präzisionsteile und Baugruppen qualifizieren.",
    "sources": "https://www.komaxgroup.com/en/annualreport2025 | https://www.komaxgroup.com/en/annualreport2025/innovation",
    "date": "2026-08-12"
  },
  {
    "company": "Bühler Group",
    "website": "https://www.buhlergroup.com/",
    "region": "Schweiz",
    "location": "Uzwil, Schweiz",
    "industry": "Lebensmittelmaschinen / Anlagenbau / Automation",
    "description": "12.090 Beschäftigte (2025)",
    "need": "2026: neue Finer S und ELK S Edition 26 mit geänderten Maschinenrahmen, IE5-Antrieben und neuer Automation.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: mittel; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "95/100",
    "priority": "A",
    "next": "Chocolate-&-Coffee-Beschaffung in Uzwil mit Bezug auf neue Edition-26-Module qualifizieren.",
    "sources": "https://annualreport.buhlergroup.com/reports/en_25/home.html | https://www.buhlergroup.com/global/en/media/media-releases/finer-s-ed-26-and-elk-s-ed-26.html",
    "date": "2026-08-12"
  },
  {
    "company": "psb intralogistics GmbH",
    "website": "https://www.psb-gmbh.de/",
    "region": "Deutschland",
    "location": "Pirmasens, Deutschland",
    "industry": "Intralogistik / Förder- und Lagertechnik",
    "description": "mehr als 520 Beschäftigte",
    "need": "2025/26: erfolgreicher Marktstart des autopick, neues Materialwirtschaftszentrum und neue automatische Lagerprojekte.",
    "fit": "Antrieb: hoch; Zahnriemen/-scheiben: hoch; CNC/Sonderteile: hoch; Baugruppen: hoch",
    "relevance": "96/100",
    "priority": "A",
    "next": "Materialwirtschaft zu Antriebselementen, Riemenscheiben und Zeichnungsteilen für Shuttle-/Sortiersysteme ansprechen.",
    "sources": "https://www.psb-gmbh.de/psb/ | https://www.psb-gmbh.de/news/ | https://www.psb-gmbh.de/news/sew-eurodrive-bruchsaal-psb-microstore/",
    "date": "2026-08-12"
  }
];
